# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline fft1d_fixed_col/VITIS_LOOP_135_2
set_directive_pipeline fft1d_fixed_col/VITIS_LOOP_151_5
set_directive_pipeline fft1d_fixed/VITIS_LOOP_103_2
set_directive_pipeline fft1d_fixed/VITIS_LOOP_119_5
set_directive_pipeline fft2d_fixed_top/anonymous
set_directive_pipeline fft2d_fixed_top/anonymous
set_directive_pipeline fft2d_fixed_top/VITIS_LOOP_182_3
set_directive_pipeline fft2d_fixed_top/VITIS_LOOP_197_7
set_directive_pipeline fft2d_fixed_top/VITIS_LOOP_191_6
set_directive_pipeline fft2d_fixed_top/VITIS_LOOP_211_11
set_directive_pipeline fft2d_fixed_top/VITIS_LOOP_205_10
set_directive_pipeline fft2d_fixed_top/VITIS_LOOP_219_14
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten fft2d_fixed_top/VITIS_LOOP_181_2
set_directive_loop_flatten fft2d_fixed_top/VITIS_LOOP_180_1
set_directive_loop_flatten fft2d_fixed_top/VITIS_LOOP_218_13
set_directive_loop_flatten fft2d_fixed_top/VITIS_LOOP_217_12
