[hls]
relative_roots=D:/zynq-2d-fft-project-2d-fft-vivado/hls/fft2d_accel
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=fft1d_fixed_col/VITIS_LOOP_135_2 
syn.directive.pipeline=fft1d_fixed_col/VITIS_LOOP_151_5 
syn.directive.pipeline=fft1d_fixed/VITIS_LOOP_103_2 
syn.directive.pipeline=fft1d_fixed/VITIS_LOOP_119_5 
syn.directive.pipeline=fft2d_fixed_top/anonymous 
syn.directive.pipeline=fft2d_fixed_top/anonymous 
syn.directive.pipeline=fft2d_fixed_top/VITIS_LOOP_182_3 
syn.directive.pipeline=fft2d_fixed_top/VITIS_LOOP_197_7 
syn.directive.pipeline=fft2d_fixed_top/VITIS_LOOP_191_6 
syn.directive.pipeline=fft2d_fixed_top/VITIS_LOOP_211_11 
syn.directive.pipeline=fft2d_fixed_top/VITIS_LOOP_205_10 
syn.directive.pipeline=fft2d_fixed_top/VITIS_LOOP_219_14 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=fft2d_fixed_top/VITIS_LOOP_181_2  
syn.directive.loop_flatten=fft2d_fixed_top/VITIS_LOOP_180_1  
syn.directive.loop_flatten=fft2d_fixed_top/VITIS_LOOP_218_13  
syn.directive.loop_flatten=fft2d_fixed_top/VITIS_LOOP_217_12  


