// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_205_10 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln206,
        zext_ln204,
        col_buffer_real_address0,
        col_buffer_real_ce0,
        col_buffer_real_we0,
        col_buffer_real_d0,
        col_buffer_imag_address0,
        col_buffer_imag_ce0,
        col_buffer_imag_we0,
        col_buffer_imag_d0,
        matrix_real_address0,
        matrix_real_ce0,
        matrix_real_q0,
        matrix_imag_address0,
        matrix_imag_ce0,
        matrix_imag_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] zext_ln206;
input  [5:0] zext_ln204;
output  [5:0] col_buffer_real_address0;
output   col_buffer_real_ce0;
output   col_buffer_real_we0;
output  [31:0] col_buffer_real_d0;
output  [5:0] col_buffer_imag_address0;
output   col_buffer_imag_ce0;
output   col_buffer_imag_we0;
output  [31:0] col_buffer_imag_d0;
output  [13:0] matrix_real_address0;
output   matrix_real_ce0;
input  [31:0] matrix_real_q0;
output  [13:0] matrix_imag_address0;
output   matrix_imag_ce0;
input  [31:0] matrix_imag_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln205_fu_122_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] r_2_reg_175;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln206_2_fu_152_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln205_fu_163_p1;
reg   [6:0] r_fu_44;
wire   [6:0] add_ln205_fu_128_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_r_2;
reg    matrix_real_ce0_local;
reg    matrix_imag_ce0_local;
reg    col_buffer_real_we0_local;
reg    col_buffer_real_ce0_local;
reg    col_buffer_imag_we0_local;
reg    col_buffer_imag_ce0_local;
wire   [7:0] zext_ln206_1_fu_134_p1;
wire   [7:0] add_ln206_fu_138_p2;
wire   [13:0] add_ln206_1_fu_144_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 r_fu_44 = 7'd0;
#0 ap_done_reg = 1'b0;
end

fft2d_fixed_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln205_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_44 <= add_ln205_fu_128_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_44 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_2_reg_175 <= ap_sig_allocacmp_r_2;
    end
end

always @ (*) begin
    if (((icmp_ln205_fu_122_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_r_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_r_2 = r_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_buffer_imag_ce0_local = 1'b1;
    end else begin
        col_buffer_imag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_buffer_imag_we0_local = 1'b1;
    end else begin
        col_buffer_imag_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_buffer_real_ce0_local = 1'b1;
    end else begin
        col_buffer_real_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_buffer_real_we0_local = 1'b1;
    end else begin
        col_buffer_real_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrix_imag_ce0_local = 1'b1;
    end else begin
        matrix_imag_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matrix_real_ce0_local = 1'b1;
    end else begin
        matrix_real_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln205_fu_128_p2 = (ap_sig_allocacmp_r_2 + 7'd1);

assign add_ln206_1_fu_144_p3 = {{add_ln206_fu_138_p2}, {zext_ln204}};

assign add_ln206_fu_138_p2 = (zext_ln206 + zext_ln206_1_fu_134_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign col_buffer_imag_address0 = zext_ln205_fu_163_p1;

assign col_buffer_imag_ce0 = col_buffer_imag_ce0_local;

assign col_buffer_imag_d0 = matrix_imag_q0;

assign col_buffer_imag_we0 = col_buffer_imag_we0_local;

assign col_buffer_real_address0 = zext_ln205_fu_163_p1;

assign col_buffer_real_ce0 = col_buffer_real_ce0_local;

assign col_buffer_real_d0 = matrix_real_q0;

assign col_buffer_real_we0 = col_buffer_real_we0_local;

assign icmp_ln205_fu_122_p2 = ((ap_sig_allocacmp_r_2 == 7'd64) ? 1'b1 : 1'b0);

assign matrix_imag_address0 = zext_ln206_2_fu_152_p1;

assign matrix_imag_ce0 = matrix_imag_ce0_local;

assign matrix_real_address0 = zext_ln206_2_fu_152_p1;

assign matrix_real_ce0 = matrix_real_ce0_local;

assign zext_ln205_fu_163_p1 = r_2_reg_175;

assign zext_ln206_1_fu_134_p1 = ap_sig_allocacmp_r_2;

assign zext_ln206_2_fu_152_p1 = add_ln206_1_fu_144_p3;

endmodule //fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_205_10
