// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module fft2d_fixed_top_fft2d_fixed_top_Outline_VITIS_LOOP_189_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        row_buffer_real_address0,
        row_buffer_real_ce0,
        row_buffer_real_we0,
        row_buffer_real_d0,
        row_buffer_real_q0,
        row_buffer_real_address1,
        row_buffer_real_ce1,
        row_buffer_real_q1,
        row_buffer_imag_address0,
        row_buffer_imag_ce0,
        row_buffer_imag_we0,
        row_buffer_imag_d0,
        row_buffer_imag_q0,
        row_buffer_imag_address1,
        row_buffer_imag_ce1,
        row_buffer_imag_q1,
        matrix_real_address0,
        matrix_real_ce0,
        matrix_real_we0,
        matrix_real_d0,
        matrix_real_q0,
        matrix_imag_address0,
        matrix_imag_ce0,
        matrix_imag_we0,
        matrix_imag_d0,
        matrix_imag_q0,
        grp_fu_480_p_din0,
        grp_fu_480_p_din1,
        grp_fu_480_p_dout0,
        grp_fu_480_p_ce,
        grp_fu_484_p_din0,
        grp_fu_484_p_din1,
        grp_fu_484_p_dout0,
        grp_fu_484_p_ce,
        grp_fu_488_p_din0,
        grp_fu_488_p_din1,
        grp_fu_488_p_dout0,
        grp_fu_488_p_ce,
        grp_fu_492_p_din0,
        grp_fu_492_p_din1,
        grp_fu_492_p_dout0,
        grp_fu_492_p_ce
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] row_buffer_real_address0;
output   row_buffer_real_ce0;
output   row_buffer_real_we0;
output  [31:0] row_buffer_real_d0;
input  [31:0] row_buffer_real_q0;
output  [5:0] row_buffer_real_address1;
output   row_buffer_real_ce1;
input  [31:0] row_buffer_real_q1;
output  [5:0] row_buffer_imag_address0;
output   row_buffer_imag_ce0;
output   row_buffer_imag_we0;
output  [31:0] row_buffer_imag_d0;
input  [31:0] row_buffer_imag_q0;
output  [5:0] row_buffer_imag_address1;
output   row_buffer_imag_ce1;
input  [31:0] row_buffer_imag_q1;
output  [13:0] matrix_real_address0;
output   matrix_real_ce0;
output   matrix_real_we0;
output  [31:0] matrix_real_d0;
input  [31:0] matrix_real_q0;
output  [13:0] matrix_imag_address0;
output   matrix_imag_ce0;
output   matrix_imag_we0;
output  [31:0] matrix_imag_d0;
input  [31:0] matrix_imag_q0;
output  [31:0] grp_fu_480_p_din0;
output  [12:0] grp_fu_480_p_din1;
input  [44:0] grp_fu_480_p_dout0;
output   grp_fu_480_p_ce;
output  [31:0] grp_fu_484_p_din0;
output  [12:0] grp_fu_484_p_din1;
input  [44:0] grp_fu_484_p_dout0;
output   grp_fu_484_p_ce;
output  [31:0] grp_fu_488_p_din0;
output  [13:0] grp_fu_488_p_din1;
input  [43:0] grp_fu_488_p_dout0;
output   grp_fu_488_p_ce;
output  [31:0] grp_fu_492_p_din0;
output  [13:0] grp_fu_492_p_din1;
input  [43:0] grp_fu_492_p_dout0;
output   grp_fu_492_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] row_buffer_real_address0;
reg row_buffer_real_ce0;
reg row_buffer_real_we0;
reg[31:0] row_buffer_real_d0;
reg row_buffer_real_ce1;
reg[5:0] row_buffer_imag_address0;
reg row_buffer_imag_ce0;
reg row_buffer_imag_we0;
reg[31:0] row_buffer_imag_d0;
reg row_buffer_imag_ce1;
reg[13:0] matrix_real_address0;
reg matrix_real_ce0;
reg matrix_real_we0;
reg[13:0] matrix_imag_address0;
reg matrix_imag_ce0;
reg matrix_imag_we0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] add_ln189_fu_117_p2;
reg   [1:0] add_ln189_reg_175;
wire    ap_CS_fsm_state2;
wire   [7:0] tmp_3_fu_123_p3;
reg   [7:0] tmp_3_reg_180;
wire   [6:0] add_ln190_fu_137_p2;
reg   [6:0] add_ln190_reg_188;
wire    ap_CS_fsm_state3;
wire   [13:0] tmp_fu_152_p3;
reg   [13:0] tmp_reg_193;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_idle;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_ready;
wire   [5:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0;
wire   [31:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0;
wire   [5:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0;
wire   [31:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0;
wire   [13:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0;
wire   [13:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0;
wire    grp_fft1d_fixed_fu_78_ap_start;
wire    grp_fft1d_fixed_fu_78_ap_done;
wire    grp_fft1d_fixed_fu_78_ap_idle;
wire    grp_fft1d_fixed_fu_78_ap_ready;
wire   [5:0] grp_fft1d_fixed_fu_78_data_real_address0;
wire    grp_fft1d_fixed_fu_78_data_real_ce0;
wire    grp_fft1d_fixed_fu_78_data_real_we0;
wire   [31:0] grp_fft1d_fixed_fu_78_data_real_d0;
wire   [5:0] grp_fft1d_fixed_fu_78_data_real_address1;
wire    grp_fft1d_fixed_fu_78_data_real_ce1;
wire   [5:0] grp_fft1d_fixed_fu_78_data_imag_address0;
wire    grp_fft1d_fixed_fu_78_data_imag_ce0;
wire    grp_fft1d_fixed_fu_78_data_imag_we0;
wire   [31:0] grp_fft1d_fixed_fu_78_data_imag_d0;
wire   [5:0] grp_fft1d_fixed_fu_78_data_imag_address1;
wire    grp_fft1d_fixed_fu_78_data_imag_ce1;
wire  signed [31:0] grp_fft1d_fixed_fu_78_grp_fu_199_p_din0;
wire  signed [12:0] grp_fft1d_fixed_fu_78_grp_fu_199_p_din1;
wire    grp_fft1d_fixed_fu_78_grp_fu_199_p_ce;
wire  signed [31:0] grp_fft1d_fixed_fu_78_grp_fu_203_p_din0;
wire  signed [12:0] grp_fft1d_fixed_fu_78_grp_fu_203_p_din1;
wire    grp_fft1d_fixed_fu_78_grp_fu_203_p_ce;
wire  signed [31:0] grp_fft1d_fixed_fu_78_grp_fu_207_p_din0;
wire  signed [13:0] grp_fft1d_fixed_fu_78_grp_fu_207_p_din1;
wire    grp_fft1d_fixed_fu_78_grp_fu_207_p_ce;
wire  signed [31:0] grp_fft1d_fixed_fu_78_grp_fu_211_p_din0;
wire  signed [13:0] grp_fft1d_fixed_fu_78_grp_fu_211_p_din1;
wire    grp_fft1d_fixed_fu_78_grp_fu_211_p_ce;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_idle;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_ready;
wire   [5:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0;
wire   [5:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0;
wire   [13:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0;
wire   [31:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_d0;
wire   [13:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0;
wire    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0;
wire   [31:0] grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_d0;
reg   [6:0] r_1_reg_54;
wire   [0:0] icmp_ln189_fu_111_p2;
wire    ap_CS_fsm_state8;
reg    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg;
wire   [0:0] icmp_ln190_fu_131_p2;
wire    ap_CS_fsm_state4;
reg    grp_fft1d_fixed_fu_78_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg;
wire    ap_CS_fsm_state7;
reg   [1:0] ch_fu_50;
wire   [7:0] zext_ln192_fu_143_p1;
wire   [7:0] add_ln192_fu_147_p2;
reg    grp_fu_199_ce;
reg    grp_fu_203_ce;
reg    grp_fu_207_ce;
reg    grp_fu_211_ce;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg = 1'b0;
#0 grp_fft1d_fixed_fu_78_ap_start_reg = 1'b0;
#0 grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg = 1'b0;
#0 ch_fu_50 = 2'd0;
end

fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6 grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start),
    .ap_done(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done),
    .ap_idle(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_idle),
    .ap_ready(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_ready),
    .empty(tmp_reg_193),
    .row_buffer_real_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0),
    .row_buffer_real_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0),
    .row_buffer_real_we0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0),
    .row_buffer_real_d0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0),
    .row_buffer_imag_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0),
    .row_buffer_imag_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0),
    .row_buffer_imag_we0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0),
    .row_buffer_imag_d0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0),
    .matrix_real_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0),
    .matrix_real_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0),
    .matrix_real_q0(matrix_real_q0),
    .matrix_imag_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0),
    .matrix_imag_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0),
    .matrix_imag_q0(matrix_imag_q0)
);

fft2d_fixed_top_fft1d_fixed grp_fft1d_fixed_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft1d_fixed_fu_78_ap_start),
    .ap_done(grp_fft1d_fixed_fu_78_ap_done),
    .ap_idle(grp_fft1d_fixed_fu_78_ap_idle),
    .ap_ready(grp_fft1d_fixed_fu_78_ap_ready),
    .data_real_address0(grp_fft1d_fixed_fu_78_data_real_address0),
    .data_real_ce0(grp_fft1d_fixed_fu_78_data_real_ce0),
    .data_real_we0(grp_fft1d_fixed_fu_78_data_real_we0),
    .data_real_d0(grp_fft1d_fixed_fu_78_data_real_d0),
    .data_real_q0(row_buffer_real_q0),
    .data_real_address1(grp_fft1d_fixed_fu_78_data_real_address1),
    .data_real_ce1(grp_fft1d_fixed_fu_78_data_real_ce1),
    .data_real_q1(row_buffer_real_q1),
    .data_imag_address0(grp_fft1d_fixed_fu_78_data_imag_address0),
    .data_imag_ce0(grp_fft1d_fixed_fu_78_data_imag_ce0),
    .data_imag_we0(grp_fft1d_fixed_fu_78_data_imag_we0),
    .data_imag_d0(grp_fft1d_fixed_fu_78_data_imag_d0),
    .data_imag_q0(row_buffer_imag_q0),
    .data_imag_address1(grp_fft1d_fixed_fu_78_data_imag_address1),
    .data_imag_ce1(grp_fft1d_fixed_fu_78_data_imag_ce1),
    .data_imag_q1(row_buffer_imag_q1),
    .grp_fu_199_p_din0(grp_fft1d_fixed_fu_78_grp_fu_199_p_din0),
    .grp_fu_199_p_din1(grp_fft1d_fixed_fu_78_grp_fu_199_p_din1),
    .grp_fu_199_p_dout0(grp_fu_480_p_dout0),
    .grp_fu_199_p_ce(grp_fft1d_fixed_fu_78_grp_fu_199_p_ce),
    .grp_fu_203_p_din0(grp_fft1d_fixed_fu_78_grp_fu_203_p_din0),
    .grp_fu_203_p_din1(grp_fft1d_fixed_fu_78_grp_fu_203_p_din1),
    .grp_fu_203_p_dout0(grp_fu_484_p_dout0),
    .grp_fu_203_p_ce(grp_fft1d_fixed_fu_78_grp_fu_203_p_ce),
    .grp_fu_207_p_din0(grp_fft1d_fixed_fu_78_grp_fu_207_p_din0),
    .grp_fu_207_p_din1(grp_fft1d_fixed_fu_78_grp_fu_207_p_din1),
    .grp_fu_207_p_dout0(grp_fu_488_p_dout0),
    .grp_fu_207_p_ce(grp_fft1d_fixed_fu_78_grp_fu_207_p_ce),
    .grp_fu_211_p_din0(grp_fft1d_fixed_fu_78_grp_fu_211_p_din0),
    .grp_fu_211_p_din1(grp_fft1d_fixed_fu_78_grp_fu_211_p_din1),
    .grp_fu_211_p_dout0(grp_fu_492_p_dout0),
    .grp_fu_211_p_ce(grp_fft1d_fixed_fu_78_grp_fu_211_p_ce)
);

fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7 grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start),
    .ap_done(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done),
    .ap_idle(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_idle),
    .ap_ready(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_ready),
    .empty(tmp_reg_193),
    .row_buffer_real_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0),
    .row_buffer_real_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0),
    .row_buffer_real_q0(row_buffer_real_q0),
    .row_buffer_imag_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0),
    .row_buffer_imag_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0),
    .row_buffer_imag_q0(row_buffer_imag_q0),
    .matrix_real_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0),
    .matrix_real_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0),
    .matrix_real_we0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0),
    .matrix_real_d0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_d0),
    .matrix_imag_address0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0),
    .matrix_imag_ce0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0),
    .matrix_imag_we0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0),
    .matrix_imag_d0(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft1d_fixed_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_fft1d_fixed_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_fft1d_fixed_fu_78_ap_ready == 1'b1)) begin
            grp_fft1d_fixed_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln190_fu_131_p2 == 1'd0))) begin
            grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg <= 1'b1;
        end else if ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_ready == 1'b1)) begin
            grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_ready == 1'b1)) begin
            grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ch_fu_50 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln190_fu_131_p2 == 1'd1))) begin
        ch_fu_50 <= add_ln189_reg_175;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done == 1'b1))) begin
        r_1_reg_54 <= add_ln190_reg_188;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_111_p2 == 1'd0))) begin
        r_1_reg_54 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln189_reg_175 <= add_ln189_fu_117_p2;
        tmp_3_reg_180[7 : 6] <= tmp_3_fu_123_p3[7 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln190_reg_188 <= add_ln190_fu_137_p2;
        tmp_reg_193[13 : 6] <= tmp_fu_152_p3[13 : 6];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_fft1d_fixed_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_111_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_111_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_199_ce = grp_fft1d_fixed_fu_78_grp_fu_199_p_ce;
    end else begin
        grp_fu_199_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_203_ce = grp_fft1d_fixed_fu_78_grp_fu_203_p_ce;
    end else begin
        grp_fu_203_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_207_ce = grp_fft1d_fixed_fu_78_grp_fu_207_p_ce;
    end else begin
        grp_fu_207_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_211_ce = grp_fft1d_fixed_fu_78_grp_fu_211_p_ce;
    end else begin
        grp_fu_211_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_imag_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        matrix_imag_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0;
    end else begin
        matrix_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_imag_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        matrix_imag_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0;
    end else begin
        matrix_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_imag_we0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0;
    end else begin
        matrix_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_real_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        matrix_real_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0;
    end else begin
        matrix_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_real_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        matrix_real_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0;
    end else begin
        matrix_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrix_real_we0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0;
    end else begin
        matrix_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        row_buffer_imag_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_imag_address0 = grp_fft1d_fixed_fu_78_data_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_imag_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0;
    end else begin
        row_buffer_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        row_buffer_imag_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_imag_ce0 = grp_fft1d_fixed_fu_78_data_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_imag_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0;
    end else begin
        row_buffer_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_imag_ce1 = grp_fft1d_fixed_fu_78_data_imag_ce1;
    end else begin
        row_buffer_imag_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_imag_d0 = grp_fft1d_fixed_fu_78_data_imag_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_imag_d0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0;
    end else begin
        row_buffer_imag_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_imag_we0 = grp_fft1d_fixed_fu_78_data_imag_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_imag_we0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0;
    end else begin
        row_buffer_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        row_buffer_real_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_real_address0 = grp_fft1d_fixed_fu_78_data_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_real_address0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0;
    end else begin
        row_buffer_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        row_buffer_real_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_real_ce0 = grp_fft1d_fixed_fu_78_data_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_real_ce0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0;
    end else begin
        row_buffer_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_real_ce1 = grp_fft1d_fixed_fu_78_data_real_ce1;
    end else begin
        row_buffer_real_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_real_d0 = grp_fft1d_fixed_fu_78_data_real_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_real_d0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0;
    end else begin
        row_buffer_real_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buffer_real_we0 = grp_fft1d_fixed_fu_78_data_real_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buffer_real_we0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0;
    end else begin
        row_buffer_real_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_111_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln190_fu_131_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_fft1d_fixed_fu_78_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln189_fu_117_p2 = (ch_fu_50 + 2'd1);

assign add_ln190_fu_137_p2 = (r_1_reg_54 + 7'd1);

assign add_ln192_fu_147_p2 = (tmp_3_reg_180 + zext_ln192_fu_143_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign grp_fft1d_fixed_fu_78_ap_start = grp_fft1d_fixed_fu_78_ap_start_reg;

assign grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg;

assign grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg;

assign grp_fu_480_p_ce = grp_fu_199_ce;

assign grp_fu_480_p_din0 = grp_fft1d_fixed_fu_78_grp_fu_199_p_din0;

assign grp_fu_480_p_din1 = grp_fft1d_fixed_fu_78_grp_fu_199_p_din1;

assign grp_fu_484_p_ce = grp_fu_203_ce;

assign grp_fu_484_p_din0 = grp_fft1d_fixed_fu_78_grp_fu_203_p_din0;

assign grp_fu_484_p_din1 = grp_fft1d_fixed_fu_78_grp_fu_203_p_din1;

assign grp_fu_488_p_ce = grp_fu_207_ce;

assign grp_fu_488_p_din0 = grp_fft1d_fixed_fu_78_grp_fu_207_p_din0;

assign grp_fu_488_p_din1 = grp_fft1d_fixed_fu_78_grp_fu_207_p_din1;

assign grp_fu_492_p_ce = grp_fu_211_ce;

assign grp_fu_492_p_din0 = grp_fft1d_fixed_fu_78_grp_fu_211_p_din0;

assign grp_fu_492_p_din1 = grp_fft1d_fixed_fu_78_grp_fu_211_p_din1;

assign icmp_ln189_fu_111_p2 = ((ch_fu_50 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_131_p2 = ((r_1_reg_54 == 7'd64) ? 1'b1 : 1'b0);

assign matrix_imag_d0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_d0;

assign matrix_real_d0 = grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_d0;

assign row_buffer_imag_address1 = grp_fft1d_fixed_fu_78_data_imag_address1;

assign row_buffer_real_address1 = grp_fft1d_fixed_fu_78_data_real_address1;

assign tmp_3_fu_123_p3 = {{ch_fu_50}, {6'd0}};

assign tmp_fu_152_p3 = {{add_ln192_fu_147_p2}, {6'd0}};

assign zext_ln192_fu_143_p1 = r_1_reg_54;

always @ (posedge ap_clk) begin
    tmp_3_reg_180[5:0] <= 6'b000000;
    tmp_reg_193[5:0] <= 6'b000000;
end

endmodule //fft2d_fixed_top_fft2d_fixed_top_Outline_VITIS_LOOP_189_4
