// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft1d_fixed (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_real_V_address0,
        data_real_V_ce0,
        data_real_V_we0,
        data_real_V_d0,
        data_real_V_q0,
        data_real_V_address1,
        data_real_V_ce1,
        data_real_V_we1,
        data_real_V_d1,
        data_real_V_q1,
        data_imag_V_address0,
        data_imag_V_ce0,
        data_imag_V_we0,
        data_imag_V_d0,
        data_imag_V_q0,
        data_imag_V_address1,
        data_imag_V_ce1,
        data_imag_V_we1,
        data_imag_V_d1,
        data_imag_V_q1
);

parameter    ap_ST_fsm_state1 = 49'd1;
parameter    ap_ST_fsm_state2 = 49'd2;
parameter    ap_ST_fsm_state3 = 49'd4;
parameter    ap_ST_fsm_state4 = 49'd8;
parameter    ap_ST_fsm_state5 = 49'd16;
parameter    ap_ST_fsm_state6 = 49'd32;
parameter    ap_ST_fsm_state7 = 49'd64;
parameter    ap_ST_fsm_state8 = 49'd128;
parameter    ap_ST_fsm_state9 = 49'd256;
parameter    ap_ST_fsm_state10 = 49'd512;
parameter    ap_ST_fsm_state11 = 49'd1024;
parameter    ap_ST_fsm_state12 = 49'd2048;
parameter    ap_ST_fsm_state13 = 49'd4096;
parameter    ap_ST_fsm_state14 = 49'd8192;
parameter    ap_ST_fsm_state15 = 49'd16384;
parameter    ap_ST_fsm_state16 = 49'd32768;
parameter    ap_ST_fsm_state17 = 49'd65536;
parameter    ap_ST_fsm_state18 = 49'd131072;
parameter    ap_ST_fsm_state19 = 49'd262144;
parameter    ap_ST_fsm_state20 = 49'd524288;
parameter    ap_ST_fsm_state21 = 49'd1048576;
parameter    ap_ST_fsm_state22 = 49'd2097152;
parameter    ap_ST_fsm_state23 = 49'd4194304;
parameter    ap_ST_fsm_state24 = 49'd8388608;
parameter    ap_ST_fsm_state25 = 49'd16777216;
parameter    ap_ST_fsm_state26 = 49'd33554432;
parameter    ap_ST_fsm_state27 = 49'd67108864;
parameter    ap_ST_fsm_state28 = 49'd134217728;
parameter    ap_ST_fsm_state29 = 49'd268435456;
parameter    ap_ST_fsm_state30 = 49'd536870912;
parameter    ap_ST_fsm_state31 = 49'd1073741824;
parameter    ap_ST_fsm_state32 = 49'd2147483648;
parameter    ap_ST_fsm_state33 = 49'd4294967296;
parameter    ap_ST_fsm_state34 = 49'd8589934592;
parameter    ap_ST_fsm_state35 = 49'd17179869184;
parameter    ap_ST_fsm_state36 = 49'd34359738368;
parameter    ap_ST_fsm_state37 = 49'd68719476736;
parameter    ap_ST_fsm_state38 = 49'd137438953472;
parameter    ap_ST_fsm_state39 = 49'd274877906944;
parameter    ap_ST_fsm_state40 = 49'd549755813888;
parameter    ap_ST_fsm_state41 = 49'd1099511627776;
parameter    ap_ST_fsm_state42 = 49'd2199023255552;
parameter    ap_ST_fsm_state43 = 49'd4398046511104;
parameter    ap_ST_fsm_state44 = 49'd8796093022208;
parameter    ap_ST_fsm_state45 = 49'd17592186044416;
parameter    ap_ST_fsm_state46 = 49'd35184372088832;
parameter    ap_ST_fsm_state47 = 49'd70368744177664;
parameter    ap_ST_fsm_state48 = 49'd140737488355328;
parameter    ap_ST_fsm_state49 = 49'd281474976710656;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] data_real_V_address0;
output   data_real_V_ce0;
output   data_real_V_we0;
output  [31:0] data_real_V_d0;
input  [31:0] data_real_V_q0;
output  [5:0] data_real_V_address1;
output   data_real_V_ce1;
output   data_real_V_we1;
output  [31:0] data_real_V_d1;
input  [31:0] data_real_V_q1;
output  [5:0] data_imag_V_address0;
output   data_imag_V_ce0;
output   data_imag_V_we0;
output  [31:0] data_imag_V_d0;
input  [31:0] data_imag_V_q0;
output  [5:0] data_imag_V_address1;
output   data_imag_V_ce1;
output   data_imag_V_we1;
output  [31:0] data_imag_V_d1;
input  [31:0] data_imag_V_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] data_real_V_address0;
reg data_real_V_ce0;
reg data_real_V_we0;
reg[31:0] data_real_V_d0;
reg[5:0] data_real_V_address1;
reg data_real_V_ce1;
reg data_real_V_we1;
reg[31:0] data_real_V_d1;
reg[5:0] data_imag_V_address0;
reg data_imag_V_ce0;
reg data_imag_V_we0;
reg[31:0] data_imag_V_d0;
reg[5:0] data_imag_V_address1;
reg data_imag_V_ce1;
reg data_imag_V_we1;
reg[31:0] data_imag_V_d1;

(* fsm_encoding = "none" *) reg   [48:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] TWIDDLE_REAL_V_address0;
reg    TWIDDLE_REAL_V_ce0;
wire   [13:0] TWIDDLE_REAL_V_q0;
wire   [4:0] TWIDDLE_IMAG_V_address0;
reg    TWIDDLE_IMAG_V_ce0;
wire   [12:0] TWIDDLE_IMAG_V_q0;
wire   [31:0] grp_fu_262_p2;
reg   [31:0] reg_267;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_28_fu_306_p2;
reg   [31:0] reg_273;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state47;
reg   [31:0] reg_279;
wire   [31:0] i_cast_fu_285_p1;
reg   [31:0] i_cast_reg_1314;
wire    ap_CS_fsm_state2;
wire  signed [29:0] tmp_19_fu_322_p1;
wire   [0:0] tmp_30_fu_326_p2;
reg   [0:0] tmp_30_reg_1330;
reg   [5:0] data_real_V_addr_reg_1334;
reg   [5:0] data_imag_V_addr_reg_1339;
reg   [5:0] data_real_V_addr_4_reg_1344;
reg   [5:0] data_imag_V_addr_4_reg_1349;
wire   [6:0] i_3_fu_343_p2;
wire    ap_CS_fsm_state5;
wire   [31:0] tmp_29_fu_403_p3;
reg   [31:0] tmp_29_reg_1362;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_fu_349_p2;
wire   [31:0] len_fu_427_p2;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_fu_421_p2;
wire   [30:0] j_7_fu_442_p2;
reg   [30:0] j_7_reg_1379;
wire    ap_CS_fsm_state8;
wire   [0:0] tmp_34_fu_437_p2;
reg   [5:0] data_real_V_addr_5_reg_1389;
reg   [5:0] data_imag_V_addr_5_reg_1395;
reg   [5:0] data_real_V_addr_6_reg_1401;
reg   [5:0] data_imag_V_addr_6_reg_1407;
wire   [31:0] i_4_fu_489_p2;
wire    ap_CS_fsm_state43;
reg  signed [13:0] w_real_V_reg_1428;
reg   [12:0] w_imag_V_reg_1434;
wire   [44:0] lhs_V_i_cast_fu_522_p2;
reg   [44:0] lhs_V_i_cast_reg_1439;
wire    ap_CS_fsm_state45;
wire   [44:0] rhs_V_i_cast_fu_528_p2;
reg   [44:0] rhs_V_i_cast_reg_1444;
wire   [44:0] r_V_fu_534_p2;
reg   [44:0] r_V_reg_1449;
wire   [44:0] tmp_78_fu_546_p1;
reg   [44:0] tmp_78_reg_1454;
wire   [31:0] tmp_79_fu_550_p1;
reg   [31:0] tmp_79_reg_1459;
wire   [31:0] tmp_80_fu_554_p1;
reg   [31:0] tmp_80_reg_1464;
reg   [0:0] p_Result_s_reg_1469;
wire    ap_CS_fsm_state46;
wire   [31:0] p_Val2_21_fu_600_p2;
reg   [31:0] p_Val2_21_reg_1475;
wire   [0:0] carry_4_fu_620_p2;
reg   [0:0] carry_4_reg_1481;
wire   [0:0] p_Result_15_fu_626_p3;
reg   [0:0] p_Result_15_reg_1487;
wire   [0:0] Range2_all_ones_fu_634_p3;
reg   [0:0] Range2_all_ones_reg_1492;
wire   [0:0] brmerge449_demorgan_s_fu_680_p2;
reg   [0:0] brmerge449_demorgan_s_reg_1498;
reg   [0:0] p_Result_16_reg_1504;
wire   [31:0] p_Val2_2_fu_732_p2;
reg   [31:0] p_Val2_2_reg_1510;
wire   [0:0] carry_6_fu_752_p2;
reg   [0:0] carry_6_reg_1516;
wire   [0:0] p_Result_18_fu_758_p3;
reg   [0:0] p_Result_18_reg_1522;
wire   [0:0] Range2_all_ones_2_fu_766_p3;
reg   [0:0] Range2_all_ones_2_reg_1527;
wire   [0:0] brmerge456_demorgan_s_fu_812_p2;
reg   [0:0] brmerge456_demorgan_s_reg_1533;
wire  signed [31:0] p_Val2_26_fu_889_p3;
reg  signed [31:0] p_Val2_26_reg_1539;
wire  signed [31:0] p_Val2_30_fu_968_p3;
reg  signed [31:0] p_Val2_30_reg_1545;
wire   [31:0] ComplexFixed_real_V_2_fu_1226_p3;
reg   [31:0] ComplexFixed_real_V_2_reg_1551;
wire    ap_CS_fsm_state48;
wire   [31:0] ComplexFixed_imag_V_2_fu_1306_p3;
reg   [31:0] ComplexFixed_imag_V_2_reg_1556;
reg   [31:0] j_reg_182;
reg   [6:0] i_reg_194;
reg  signed [29:0] bit_reg_206;
wire   [0:0] exitcond_fu_289_p2;
reg   [31:0] j_1_reg_217;
reg   [31:0] len_assign_reg_227;
reg   [31:0] i1_reg_239;
reg   [30:0] j_assign_reg_251;
wire    ap_CS_fsm_state49;
wire   [63:0] tmp_32_fu_331_p1;
wire   [63:0] tmp_33_fu_337_p1;
wire  signed [63:0] tmp_36_fu_472_p1;
wire  signed [63:0] tmp_38_fu_483_p1;
wire  signed [63:0] tmp_1_i_fu_495_p1;
wire   [31:0] ComplexFixed_real_V_s_fu_1056_p3;
wire   [31:0] ComplexFixed_imag_V_s_fu_1145_p3;
wire  signed [31:0] bit_cast_fu_295_p1;
wire   [31:0] tmp_s_fu_300_p2;
wire   [28:0] tmp_67_fu_312_p4;
wire   [31:0] p_neg_fu_363_p2;
wire   [30:0] p_lshr_fu_369_p4;
wire   [31:0] tmp_39_fu_379_p1;
wire   [30:0] p_lshr_f_fu_389_p4;
wire   [0:0] tmp_66_fu_355_p3;
wire   [31:0] p_neg_t_fu_383_p2;
wire   [31:0] tmp_40_fu_399_p1;
wire   [25:0] tmp_68_fu_411_p4;
wire   [31:0] j_assign_cast_fu_433_p1;
wire   [25:0] tmp_70_fu_448_p1;
wire   [31:0] grp_fu_460_p0;
wire  signed [31:0] tmp_35_fu_466_p2;
wire   [31:0] tmp_37_fu_478_p2;
wire   [31:0] grp_fu_460_p2;
wire  signed [31:0] r_V_i_cast_cast_fu_501_p0;
wire  signed [31:0] r_V_2_i_cast_cast_fu_511_p0;
wire  signed [31:0] tmp_24_fu_518_p0;
wire  signed [31:0] lhs_V_i_cast_fu_522_p0;
wire  signed [44:0] r_V_i_cast_cast_fu_501_p1;
wire  signed [13:0] lhs_V_i_cast_fu_522_p1;
wire  signed [31:0] rhs_V_i_cast_fu_528_p0;
wire  signed [12:0] rhs_V_i_cast_fu_528_p1;
wire  signed [44:0] tmp_42_i_cast_cast_fu_515_p1;
wire  signed [12:0] r_V_fu_534_p0;
wire  signed [31:0] r_V_fu_534_p1;
wire  signed [31:0] r_V_4_fu_540_p0;
wire  signed [13:0] r_V_4_fu_540_p1;
wire   [45:0] r_V_4_fu_540_p2;
wire   [44:0] ret_V_fu_558_p2;
wire   [0:0] tmp_73_fu_588_p3;
wire   [31:0] p_Val2_20_fu_570_p4;
wire   [31:0] tmp_46_i_cast_fu_596_p1;
wire   [0:0] tmp_74_fu_606_p3;
wire   [0:0] p_Result_14_fu_580_p3;
wire   [0:0] rev_fu_614_p2;
wire   [0:0] tmp_77_fu_642_p3;
wire   [0:0] p_not_fu_656_p2;
wire   [0:0] not_carry_4_fu_662_p2;
wire   [0:0] rev4_fu_650_p2;
wire   [0:0] p_i_fu_668_p2;
wire   [0:0] deleted_ones_fu_674_p2;
wire   [44:0] ret_V_6_fu_686_p2;
wire   [31:0] tmp_52_i_fu_708_p2;
wire   [0:0] tmp_83_fu_720_p3;
wire   [31:0] tmp_54_i_cast_fu_728_p1;
wire   [31:0] p_Val2_1_fu_698_p4;
wire   [0:0] tmp_84_fu_738_p3;
wire   [0:0] p_Result_17_fu_712_p3;
wire   [0:0] rev5_fu_746_p2;
wire   [0:0] tmp_87_fu_774_p3;
wire   [0:0] p_not2_fu_788_p2;
wire   [0:0] not_carry_6_fu_794_p2;
wire   [0:0] rev6_fu_782_p2;
wire   [0:0] p_3_i_fu_800_p2;
wire   [0:0] deleted_ones_6_fu_806_p2;
wire   [0:0] p_not_i_fu_822_p2;
wire   [0:0] brmerge_i_fu_826_p2;
wire   [0:0] tmp_50_i_fu_831_p2;
wire   [0:0] phitmp446_demorgan_s_fu_818_p2;
wire   [0:0] tmp27_demorgan_fu_842_p2;
wire   [0:0] tmp27_fu_847_p2;
wire   [0:0] underflow_fu_853_p2;
wire   [0:0] overflow_fu_836_p2;
wire   [0:0] tmp28_fu_864_p2;
wire   [0:0] brmerge5_i_fu_858_p2;
wire   [0:0] underflow_not_i_fu_869_p2;
wire   [31:0] p_Val2_11_mux_i_fu_875_p3;
wire   [31:0] p_Val2_i_fu_882_p3;
wire   [0:0] p_not1_i_fu_901_p2;
wire   [0:0] brmerge6_i_fu_905_p2;
wire   [0:0] tmp_58_i_fu_910_p2;
wire   [0:0] phitmp_demorgan_i_fu_897_p2;
wire   [0:0] tmp29_demorgan_fu_921_p2;
wire   [0:0] tmp29_fu_926_p2;
wire   [0:0] underflow_6_fu_932_p2;
wire   [0:0] overflow_2_fu_915_p2;
wire   [0:0] tmp30_fu_943_p2;
wire   [0:0] brmerge8_i_fu_937_p2;
wire   [0:0] underflow_2_not_i_fu_948_p2;
wire   [31:0] p_Val2_16_mux_i_fu_954_p3;
wire   [31:0] p_Val2_1_i_fu_961_p3;
wire  signed [31:0] lhs_V_fu_976_p0;
wire  signed [32:0] lhs_V_fu_976_p1;
wire  signed [32:0] rhs_V_fu_980_p1;
wire   [32:0] ret_V_7_fu_983_p2;
wire  signed [31:0] p_Val2_28_fu_997_p1;
wire   [31:0] p_Val2_28_fu_997_p2;
wire   [0:0] p_Result_20_fu_1002_p3;
wire   [0:0] p_Result_19_fu_989_p3;
wire   [0:0] tmp_59_i_fu_1010_p2;
wire   [0:0] p_Result_not_i_fu_1028_p2;
wire   [0:0] brmerge9_i_fu_1022_p2;
wire   [0:0] underflow_7_fu_1016_p2;
wire   [0:0] brmerge3_i_fu_1034_p2;
wire   [31:0] p_Val2_19_mux_i_fu_1040_p3;
wire   [31:0] p_Val2_i7_fu_1048_p3;
wire  signed [31:0] lhs_V_2_fu_1065_p0;
wire  signed [32:0] lhs_V_2_fu_1065_p1;
wire  signed [32:0] rhs_V_2_fu_1069_p1;
wire   [32:0] ret_V_8_fu_1072_p2;
wire  signed [31:0] p_Val2_32_fu_1086_p1;
wire   [31:0] p_Val2_32_fu_1086_p2;
wire   [0:0] p_Result_22_fu_1091_p3;
wire   [0:0] p_Result_21_fu_1078_p3;
wire   [0:0] tmp_61_i_fu_1099_p2;
wire   [0:0] p_Result_14_not_i_fu_1117_p2;
wire   [0:0] brmerge2_i_fu_1111_p2;
wire   [0:0] underflow_8_fu_1105_p2;
wire   [0:0] brmerge4_i9_fu_1123_p2;
wire   [31:0] p_Val2_23_mux_i_fu_1129_p3;
wire   [31:0] p_Val2_2_i_fu_1137_p3;
wire   [32:0] ret_V_9_fu_1154_p2;
wire   [0:0] p_Result_24_fu_1172_p3;
wire   [0:0] p_Result_23_fu_1160_p3;
wire   [0:0] tmp_39_i_fu_1180_p2;
wire   [0:0] p_Result_not_i2_fu_1198_p2;
wire   [0:0] brmerge1_i_fu_1192_p2;
wire   [31:0] p_Val2_34_fu_1168_p1;
wire   [0:0] underflow_9_fu_1186_p2;
wire   [0:0] brmerge4_i_fu_1204_p2;
wire   [31:0] p_Val2_3_mux_i_fu_1210_p3;
wire   [31:0] p_Val2_3_i_fu_1218_p3;
wire   [32:0] ret_V_10_fu_1234_p2;
wire   [0:0] p_Result_26_fu_1252_p3;
wire   [0:0] p_Result_25_fu_1240_p3;
wire   [0:0] tmp_41_i_fu_1260_p2;
wire   [0:0] p_Result_2_not_i_fu_1278_p2;
wire   [0:0] brmerge3_i2_fu_1272_p2;
wire   [31:0] p_Val2_36_fu_1248_p1;
wire   [0:0] underflow_10_fu_1266_p2;
wire   [0:0] brmerge5_i2_fu_1284_p2;
wire   [31:0] p_Val2_7_mux_i_fu_1290_p3;
wire   [31:0] p_Val2_7_i_fu_1298_p3;
reg    grp_fu_460_ap_start;
wire    grp_fu_460_ap_done;
reg   [48:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 49'd1;
end

fft1d_fixed_TWIDDbkb #(
    .DataWidth( 14 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
TWIDDLE_REAL_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TWIDDLE_REAL_V_address0),
    .ce0(TWIDDLE_REAL_V_ce0),
    .q0(TWIDDLE_REAL_V_q0)
);

fft1d_fixed_TWIDDcud #(
    .DataWidth( 13 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
TWIDDLE_IMAG_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TWIDDLE_IMAG_V_address0),
    .ce0(TWIDDLE_IMAG_V_ce0),
    .q0(TWIDDLE_IMAG_V_q0)
);

fft2d_fixed_top_sdEe #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fft2d_fixed_top_sdEe_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_460_ap_start),
    .done(grp_fu_460_ap_done),
    .din0(grp_fu_460_p0),
    .din1(len_assign_reg_227),
    .ce(1'b1),
    .dout(grp_fu_460_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_289_p2 == 1'd0))) begin
        bit_reg_206 <= 30'd32;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_28_fu_306_p2 == 1'd0))) begin
        bit_reg_206 <= tmp_19_fu_322_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (tmp_34_fu_437_p2 == 1'd0))) begin
        i1_reg_239 <= i_4_fu_489_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (tmp_fu_349_p2 == 1'd0))) begin
        i1_reg_239 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_reg_194 <= i_3_fu_343_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_194 <= 7'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_289_p2 == 1'd0))) begin
        j_1_reg_217 <= j_reg_182;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_28_fu_306_p2 == 1'd0))) begin
        j_1_reg_217 <= grp_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_fu_421_p2 == 1'd1))) begin
        j_assign_reg_251 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        j_assign_reg_251 <= j_7_reg_1379;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_182 <= reg_267;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_reg_182 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_289_p2 == 1'd1))) begin
                len_assign_reg_227[1] <= 1'b1;
        len_assign_reg_227[2] <= 1'b0;
        len_assign_reg_227[3] <= 1'b0;
        len_assign_reg_227[4] <= 1'b0;
        len_assign_reg_227[5] <= 1'b0;
        len_assign_reg_227[6] <= 1'b0;
        len_assign_reg_227[7] <= 1'b0;
        len_assign_reg_227[8] <= 1'b0;
        len_assign_reg_227[9] <= 1'b0;
        len_assign_reg_227[10] <= 1'b0;
        len_assign_reg_227[11] <= 1'b0;
        len_assign_reg_227[12] <= 1'b0;
        len_assign_reg_227[13] <= 1'b0;
        len_assign_reg_227[14] <= 1'b0;
        len_assign_reg_227[15] <= 1'b0;
        len_assign_reg_227[16] <= 1'b0;
        len_assign_reg_227[17] <= 1'b0;
        len_assign_reg_227[18] <= 1'b0;
        len_assign_reg_227[19] <= 1'b0;
        len_assign_reg_227[20] <= 1'b0;
        len_assign_reg_227[21] <= 1'b0;
        len_assign_reg_227[22] <= 1'b0;
        len_assign_reg_227[23] <= 1'b0;
        len_assign_reg_227[24] <= 1'b0;
        len_assign_reg_227[25] <= 1'b0;
        len_assign_reg_227[26] <= 1'b0;
        len_assign_reg_227[27] <= 1'b0;
        len_assign_reg_227[28] <= 1'b0;
        len_assign_reg_227[29] <= 1'b0;
        len_assign_reg_227[30] <= 1'b0;
        len_assign_reg_227[31] <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_fu_421_p2 == 1'd0))) begin
                len_assign_reg_227[31 : 1] <= len_fu_427_p2[31 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        reg_273 <= data_real_V_q1;
    end else if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_273 <= data_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        reg_279 <= data_imag_V_q1;
    end else if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_279 <= data_imag_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        ComplexFixed_imag_V_2_reg_1556 <= ComplexFixed_imag_V_2_fu_1306_p3;
        ComplexFixed_real_V_2_reg_1551 <= ComplexFixed_real_V_2_fu_1226_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        Range2_all_ones_2_reg_1527 <= ret_V_6_fu_686_p2[32'd44];
        Range2_all_ones_reg_1492 <= ret_V_fu_558_p2[32'd44];
        brmerge449_demorgan_s_reg_1498 <= brmerge449_demorgan_s_fu_680_p2;
        brmerge456_demorgan_s_reg_1533 <= brmerge456_demorgan_s_fu_812_p2;
        carry_4_reg_1481 <= carry_4_fu_620_p2;
        carry_6_reg_1516 <= carry_6_fu_752_p2;
        p_Result_15_reg_1487 <= p_Val2_21_fu_600_p2[32'd31];
        p_Result_16_reg_1504 <= ret_V_6_fu_686_p2[32'd44];
        p_Result_18_reg_1522 <= p_Val2_2_fu_732_p2[32'd31];
        p_Result_s_reg_1469 <= ret_V_fu_558_p2[32'd44];
        p_Val2_21_reg_1475 <= p_Val2_21_fu_600_p2;
        p_Val2_2_reg_1510 <= p_Val2_2_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_30_fu_326_p2 == 1'd1) & (tmp_28_fu_306_p2 == 1'd1))) begin
        data_imag_V_addr_4_reg_1349 <= tmp_33_fu_337_p1;
        data_imag_V_addr_reg_1339 <= tmp_32_fu_331_p1;
        data_real_V_addr_4_reg_1344 <= tmp_33_fu_337_p1;
        data_real_V_addr_reg_1334 <= tmp_32_fu_331_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (tmp_34_fu_437_p2 == 1'd1))) begin
        data_imag_V_addr_5_reg_1395 <= tmp_36_fu_472_p1;
        data_imag_V_addr_6_reg_1407 <= tmp_38_fu_483_p1;
        data_real_V_addr_5_reg_1389 <= tmp_36_fu_472_p1;
        data_real_V_addr_6_reg_1401 <= tmp_38_fu_483_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_cast_reg_1314[6 : 0] <= i_cast_fu_285_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        j_7_reg_1379 <= j_7_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        lhs_V_i_cast_reg_1439 <= lhs_V_i_cast_fu_522_p2;
        r_V_reg_1449 <= r_V_fu_534_p2;
        rhs_V_i_cast_reg_1444 <= rhs_V_i_cast_fu_528_p2;
        tmp_78_reg_1454 <= tmp_78_fu_546_p1;
        tmp_79_reg_1459 <= tmp_79_fu_550_p1;
        tmp_80_reg_1464 <= tmp_80_fu_554_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        p_Val2_26_reg_1539 <= p_Val2_26_fu_889_p3;
        p_Val2_30_reg_1545 <= p_Val2_30_fu_968_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (tmp_28_fu_306_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_28_fu_306_p2 == 1'd0)))) begin
        reg_267 <= grp_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_fu_349_p2 == 1'd0))) begin
        tmp_29_reg_1362 <= tmp_29_fu_403_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_28_fu_306_p2 == 1'd1))) begin
        tmp_30_reg_1330 <= tmp_30_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        w_imag_V_reg_1434 <= TWIDDLE_IMAG_V_q0;
        w_real_V_reg_1428 <= TWIDDLE_REAL_V_q0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        TWIDDLE_IMAG_V_ce0 = 1'b1;
    end else begin
        TWIDDLE_IMAG_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        TWIDDLE_REAL_V_ce0 = 1'b1;
    end else begin
        TWIDDLE_REAL_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state6) & (tmp_fu_349_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_fu_349_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        data_imag_V_address0 = data_imag_V_addr_5_reg_1395;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        data_imag_V_address0 = data_imag_V_addr_6_reg_1407;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_imag_V_address0 = data_imag_V_addr_reg_1339;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_imag_V_address0 = tmp_32_fu_331_p1;
    end else begin
        data_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        data_imag_V_address1 = data_imag_V_addr_6_reg_1407;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        data_imag_V_address1 = data_imag_V_addr_5_reg_1395;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_imag_V_address1 = data_imag_V_addr_4_reg_1349;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_imag_V_address1 = tmp_33_fu_337_p1;
    end else begin
        data_imag_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data_imag_V_ce0 = 1'b1;
    end else begin
        data_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        data_imag_V_ce1 = 1'b1;
    end else begin
        data_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        data_imag_V_d0 = ComplexFixed_imag_V_s_fu_1145_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_imag_V_d0 = data_imag_V_q1;
    end else begin
        data_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        data_imag_V_d1 = ComplexFixed_imag_V_2_reg_1556;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_imag_V_d1 = reg_279;
    end else begin
        data_imag_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state4))) begin
        data_imag_V_we0 = 1'b1;
    end else begin
        data_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | ((1'b1 == ap_CS_fsm_state5) & (tmp_30_reg_1330 == 1'd1)))) begin
        data_imag_V_we1 = 1'b1;
    end else begin
        data_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        data_real_V_address0 = data_real_V_addr_5_reg_1389;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        data_real_V_address0 = data_real_V_addr_6_reg_1401;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_real_V_address0 = data_real_V_addr_reg_1334;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_real_V_address0 = tmp_32_fu_331_p1;
    end else begin
        data_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        data_real_V_address1 = data_real_V_addr_6_reg_1401;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        data_real_V_address1 = data_real_V_addr_5_reg_1389;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_real_V_address1 = data_real_V_addr_4_reg_1344;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_real_V_address1 = tmp_33_fu_337_p1;
    end else begin
        data_real_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data_real_V_ce0 = 1'b1;
    end else begin
        data_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        data_real_V_ce1 = 1'b1;
    end else begin
        data_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        data_real_V_d0 = ComplexFixed_real_V_s_fu_1056_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_real_V_d0 = data_real_V_q1;
    end else begin
        data_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        data_real_V_d1 = ComplexFixed_real_V_2_reg_1551;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_real_V_d1 = reg_273;
    end else begin
        data_real_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state4))) begin
        data_real_V_we0 = 1'b1;
    end else begin
        data_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | ((1'b1 == ap_CS_fsm_state5) & (tmp_30_reg_1330 == 1'd1)))) begin
        data_real_V_we1 = 1'b1;
    end else begin
        data_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (tmp_34_fu_437_p2 == 1'd1))) begin
        grp_fu_460_ap_start = 1'b1;
    end else begin
        grp_fu_460_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_289_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (tmp_30_fu_326_p2 == 1'd0) & (tmp_28_fu_306_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_30_fu_326_p2 == 1'd1) & (tmp_28_fu_306_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (tmp_fu_349_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_fu_421_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (tmp_34_fu_437_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ComplexFixed_imag_V_2_fu_1306_p3 = ((brmerge5_i2_fu_1284_p2[0:0] === 1'b1) ? p_Val2_7_mux_i_fu_1290_p3 : p_Val2_7_i_fu_1298_p3);

assign ComplexFixed_imag_V_s_fu_1145_p3 = ((brmerge4_i9_fu_1123_p2[0:0] === 1'b1) ? p_Val2_23_mux_i_fu_1129_p3 : p_Val2_2_i_fu_1137_p3);

assign ComplexFixed_real_V_2_fu_1226_p3 = ((brmerge4_i_fu_1204_p2[0:0] === 1'b1) ? p_Val2_3_mux_i_fu_1210_p3 : p_Val2_3_i_fu_1218_p3);

assign ComplexFixed_real_V_s_fu_1056_p3 = ((brmerge3_i_fu_1034_p2[0:0] === 1'b1) ? p_Val2_19_mux_i_fu_1040_p3 : p_Val2_i7_fu_1048_p3);

assign Range2_all_ones_2_fu_766_p3 = ret_V_6_fu_686_p2[32'd44];

assign Range2_all_ones_fu_634_p3 = ret_V_fu_558_p2[32'd44];

assign TWIDDLE_IMAG_V_address0 = tmp_1_i_fu_495_p1;

assign TWIDDLE_REAL_V_address0 = tmp_1_i_fu_495_p1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign bit_cast_fu_295_p1 = bit_reg_206;

assign brmerge1_i_fu_1192_p2 = (p_Result_24_fu_1172_p3 ^ p_Result_23_fu_1160_p3);

assign brmerge2_i_fu_1111_p2 = (p_Result_22_fu_1091_p3 ^ p_Result_21_fu_1078_p3);

assign brmerge3_i2_fu_1272_p2 = (p_Result_26_fu_1252_p3 ^ p_Result_25_fu_1240_p3);

assign brmerge3_i_fu_1034_p2 = (p_Result_not_i_fu_1028_p2 | p_Result_20_fu_1002_p3);

assign brmerge449_demorgan_s_fu_680_p2 = (p_Result_15_fu_626_p3 & deleted_ones_fu_674_p2);

assign brmerge456_demorgan_s_fu_812_p2 = (p_Result_18_fu_758_p3 & deleted_ones_6_fu_806_p2);

assign brmerge4_i9_fu_1123_p2 = (p_Result_22_fu_1091_p3 | p_Result_14_not_i_fu_1117_p2);

assign brmerge4_i_fu_1204_p2 = (p_Result_not_i2_fu_1198_p2 | p_Result_24_fu_1172_p3);

assign brmerge5_i2_fu_1284_p2 = (p_Result_2_not_i_fu_1278_p2 | p_Result_26_fu_1252_p3);

assign brmerge5_i_fu_858_p2 = (underflow_fu_853_p2 | overflow_fu_836_p2);

assign brmerge6_i_fu_905_p2 = (p_not1_i_fu_901_p2 | p_Result_18_reg_1522);

assign brmerge8_i_fu_937_p2 = (underflow_6_fu_932_p2 | overflow_2_fu_915_p2);

assign brmerge9_i_fu_1022_p2 = (p_Result_20_fu_1002_p3 ^ p_Result_19_fu_989_p3);

assign brmerge_i_fu_826_p2 = (p_not_i_fu_822_p2 | p_Result_15_reg_1487);

assign carry_4_fu_620_p2 = (rev_fu_614_p2 & p_Result_14_fu_580_p3);

assign carry_6_fu_752_p2 = (rev5_fu_746_p2 & p_Result_17_fu_712_p3);

assign deleted_ones_6_fu_806_p2 = (p_3_i_fu_800_p2 & Range2_all_ones_2_fu_766_p3);

assign deleted_ones_fu_674_p2 = (p_i_fu_668_p2 & Range2_all_ones_fu_634_p3);

assign exitcond_fu_289_p2 = ((i_reg_194 == 7'd64) ? 1'b1 : 1'b0);

assign grp_fu_262_p2 = (j_1_reg_217 ^ bit_cast_fu_295_p1);

assign grp_fu_460_p0 = {{tmp_70_fu_448_p1}, {6'd0}};

assign i_3_fu_343_p2 = (i_reg_194 + 7'd1);

assign i_4_fu_489_p2 = (len_assign_reg_227 + i1_reg_239);

assign i_cast_fu_285_p1 = i_reg_194;

assign icmp_fu_421_p2 = (($signed(tmp_68_fu_411_p4) < $signed(26'd1)) ? 1'b1 : 1'b0);

assign j_7_fu_442_p2 = (j_assign_reg_251 + 31'd1);

assign j_assign_cast_fu_433_p1 = j_assign_reg_251;

assign len_fu_427_p2 = len_assign_reg_227 << 32'd1;

assign lhs_V_2_fu_1065_p0 = reg_279;

assign lhs_V_2_fu_1065_p1 = lhs_V_2_fu_1065_p0;

assign lhs_V_fu_976_p0 = reg_273;

assign lhs_V_fu_976_p1 = lhs_V_fu_976_p0;

assign lhs_V_i_cast_fu_522_p0 = r_V_i_cast_cast_fu_501_p1;

assign lhs_V_i_cast_fu_522_p1 = w_real_V_reg_1428;

assign lhs_V_i_cast_fu_522_p2 = ($signed(lhs_V_i_cast_fu_522_p0) * $signed(lhs_V_i_cast_fu_522_p1));

assign not_carry_4_fu_662_p2 = (tmp_74_fu_606_p3 | p_not_fu_656_p2);

assign not_carry_6_fu_794_p2 = (tmp_84_fu_738_p3 | p_not2_fu_788_p2);

assign overflow_2_fu_915_p2 = (tmp_58_i_fu_910_p2 & brmerge6_i_fu_905_p2);

assign overflow_fu_836_p2 = (tmp_50_i_fu_831_p2 & brmerge_i_fu_826_p2);

assign p_3_i_fu_800_p2 = (rev6_fu_782_p2 | not_carry_6_fu_794_p2);

assign p_Result_14_fu_580_p3 = ret_V_fu_558_p2[32'd43];

assign p_Result_14_not_i_fu_1117_p2 = (p_Result_21_fu_1078_p3 ^ 1'd1);

assign p_Result_15_fu_626_p3 = p_Val2_21_fu_600_p2[32'd31];

assign p_Result_17_fu_712_p3 = ret_V_6_fu_686_p2[32'd43];

assign p_Result_18_fu_758_p3 = p_Val2_2_fu_732_p2[32'd31];

assign p_Result_19_fu_989_p3 = ret_V_7_fu_983_p2[32'd32];

assign p_Result_20_fu_1002_p3 = p_Val2_28_fu_997_p2[32'd31];

assign p_Result_21_fu_1078_p3 = ret_V_8_fu_1072_p2[32'd32];

assign p_Result_22_fu_1091_p3 = p_Val2_32_fu_1086_p2[32'd31];

assign p_Result_23_fu_1160_p3 = ret_V_9_fu_1154_p2[32'd32];

assign p_Result_24_fu_1172_p3 = ret_V_9_fu_1154_p2[32'd31];

assign p_Result_25_fu_1240_p3 = ret_V_10_fu_1234_p2[32'd32];

assign p_Result_26_fu_1252_p3 = ret_V_10_fu_1234_p2[32'd31];

assign p_Result_2_not_i_fu_1278_p2 = (p_Result_25_fu_1240_p3 ^ 1'd1);

assign p_Result_not_i2_fu_1198_p2 = (p_Result_23_fu_1160_p3 ^ 1'd1);

assign p_Result_not_i_fu_1028_p2 = (p_Result_19_fu_989_p3 ^ 1'd1);

assign p_Val2_11_mux_i_fu_875_p3 = ((brmerge5_i_fu_858_p2[0:0] === 1'b1) ? 32'd2147483647 : p_Val2_21_reg_1475);

assign p_Val2_16_mux_i_fu_954_p3 = ((brmerge8_i_fu_937_p2[0:0] === 1'b1) ? 32'd2147483647 : p_Val2_2_reg_1510);

assign p_Val2_19_mux_i_fu_1040_p3 = ((brmerge9_i_fu_1022_p2[0:0] === 1'b1) ? 32'd2147483647 : p_Val2_28_fu_997_p2);

assign p_Val2_1_fu_698_p4 = {{ret_V_6_fu_686_p2[43:12]}};

assign p_Val2_1_i_fu_961_p3 = ((underflow_6_fu_932_p2[0:0] === 1'b1) ? 32'd2147483648 : p_Val2_2_reg_1510);

assign p_Val2_20_fu_570_p4 = {{ret_V_fu_558_p2[43:12]}};

assign p_Val2_21_fu_600_p2 = (p_Val2_20_fu_570_p4 + tmp_46_i_cast_fu_596_p1);

assign p_Val2_23_mux_i_fu_1129_p3 = ((brmerge2_i_fu_1111_p2[0:0] === 1'b1) ? 32'd2147483647 : p_Val2_32_fu_1086_p2);

assign p_Val2_26_fu_889_p3 = ((underflow_not_i_fu_869_p2[0:0] === 1'b1) ? p_Val2_11_mux_i_fu_875_p3 : p_Val2_i_fu_882_p3);

assign p_Val2_28_fu_997_p1 = reg_273;

assign p_Val2_28_fu_997_p2 = ($signed(p_Val2_26_reg_1539) + $signed(p_Val2_28_fu_997_p1));

assign p_Val2_2_fu_732_p2 = (tmp_54_i_cast_fu_728_p1 + p_Val2_1_fu_698_p4);

assign p_Val2_2_i_fu_1137_p3 = ((underflow_8_fu_1105_p2[0:0] === 1'b1) ? 32'd2147483648 : p_Val2_32_fu_1086_p2);

assign p_Val2_30_fu_968_p3 = ((underflow_2_not_i_fu_948_p2[0:0] === 1'b1) ? p_Val2_16_mux_i_fu_954_p3 : p_Val2_1_i_fu_961_p3);

assign p_Val2_32_fu_1086_p1 = reg_279;

assign p_Val2_32_fu_1086_p2 = ($signed(p_Val2_30_reg_1545) + $signed(p_Val2_32_fu_1086_p1));

assign p_Val2_34_fu_1168_p1 = ret_V_9_fu_1154_p2[31:0];

assign p_Val2_36_fu_1248_p1 = ret_V_10_fu_1234_p2[31:0];

assign p_Val2_3_i_fu_1218_p3 = ((underflow_9_fu_1186_p2[0:0] === 1'b1) ? 32'd2147483648 : p_Val2_34_fu_1168_p1);

assign p_Val2_3_mux_i_fu_1210_p3 = ((brmerge1_i_fu_1192_p2[0:0] === 1'b1) ? 32'd2147483647 : p_Val2_34_fu_1168_p1);

assign p_Val2_7_i_fu_1298_p3 = ((underflow_10_fu_1266_p2[0:0] === 1'b1) ? 32'd2147483648 : p_Val2_36_fu_1248_p1);

assign p_Val2_7_mux_i_fu_1290_p3 = ((brmerge3_i2_fu_1272_p2[0:0] === 1'b1) ? 32'd2147483647 : p_Val2_36_fu_1248_p1);

assign p_Val2_i7_fu_1048_p3 = ((underflow_7_fu_1016_p2[0:0] === 1'b1) ? 32'd2147483648 : p_Val2_28_fu_997_p2);

assign p_Val2_i_fu_882_p3 = ((underflow_fu_853_p2[0:0] === 1'b1) ? 32'd2147483648 : p_Val2_21_reg_1475);

assign p_i_fu_668_p2 = (rev4_fu_650_p2 | not_carry_4_fu_662_p2);

assign p_lshr_f_fu_389_p4 = {{len_assign_reg_227[31:1]}};

assign p_lshr_fu_369_p4 = {{p_neg_fu_363_p2[31:1]}};

assign p_neg_fu_363_p2 = (32'd0 - len_assign_reg_227);

assign p_neg_t_fu_383_p2 = (32'd0 - tmp_39_fu_379_p1);

assign p_not1_i_fu_901_p2 = (carry_6_reg_1516 ^ Range2_all_ones_2_reg_1527);

assign p_not2_fu_788_p2 = (p_Result_17_fu_712_p3 ^ 1'd1);

assign p_not_fu_656_p2 = (p_Result_14_fu_580_p3 ^ 1'd1);

assign p_not_i_fu_822_p2 = (carry_4_reg_1481 ^ Range2_all_ones_reg_1492);

assign phitmp446_demorgan_s_fu_818_p2 = (carry_4_reg_1481 & Range2_all_ones_reg_1492);

assign phitmp_demorgan_i_fu_897_p2 = (carry_6_reg_1516 & Range2_all_ones_2_reg_1527);

assign r_V_2_i_cast_cast_fu_511_p0 = reg_279;

assign r_V_4_fu_540_p0 = r_V_2_i_cast_cast_fu_511_p0;

assign r_V_4_fu_540_p1 = w_real_V_reg_1428;

assign r_V_4_fu_540_p2 = ($signed(r_V_4_fu_540_p0) * $signed(r_V_4_fu_540_p1));

assign r_V_fu_534_p0 = tmp_42_i_cast_cast_fu_515_p1;

assign r_V_fu_534_p1 = r_V_i_cast_cast_fu_501_p1;

assign r_V_fu_534_p2 = ($signed(r_V_fu_534_p0) * $signed(r_V_fu_534_p1));

assign r_V_i_cast_cast_fu_501_p0 = reg_273;

assign r_V_i_cast_cast_fu_501_p1 = r_V_i_cast_cast_fu_501_p0;

assign ret_V_10_fu_1234_p2 = ($signed(lhs_V_2_fu_1065_p1) - $signed(rhs_V_2_fu_1069_p1));

assign ret_V_6_fu_686_p2 = (r_V_reg_1449 + tmp_78_reg_1454);

assign ret_V_7_fu_983_p2 = ($signed(lhs_V_fu_976_p1) + $signed(rhs_V_fu_980_p1));

assign ret_V_8_fu_1072_p2 = ($signed(lhs_V_2_fu_1065_p1) + $signed(rhs_V_2_fu_1069_p1));

assign ret_V_9_fu_1154_p2 = ($signed(lhs_V_fu_976_p1) - $signed(rhs_V_fu_980_p1));

assign ret_V_fu_558_p2 = (lhs_V_i_cast_reg_1439 - rhs_V_i_cast_reg_1444);

assign rev4_fu_650_p2 = (tmp_77_fu_642_p3 ^ 1'd1);

assign rev5_fu_746_p2 = (tmp_84_fu_738_p3 ^ 1'd1);

assign rev6_fu_782_p2 = (tmp_87_fu_774_p3 ^ 1'd1);

assign rev_fu_614_p2 = (tmp_74_fu_606_p3 ^ 1'd1);

assign rhs_V_2_fu_1069_p1 = p_Val2_30_reg_1545;

assign rhs_V_fu_980_p1 = p_Val2_26_reg_1539;

assign rhs_V_i_cast_fu_528_p0 = tmp_24_fu_518_p0;

assign rhs_V_i_cast_fu_528_p1 = tmp_42_i_cast_cast_fu_515_p1;

assign rhs_V_i_cast_fu_528_p2 = ($signed(rhs_V_i_cast_fu_528_p0) * $signed(rhs_V_i_cast_fu_528_p1));

assign tmp27_demorgan_fu_842_p2 = (phitmp446_demorgan_s_fu_818_p2 | brmerge449_demorgan_s_reg_1498);

assign tmp27_fu_847_p2 = (tmp27_demorgan_fu_842_p2 ^ 1'd1);

assign tmp28_fu_864_p2 = (tmp_50_i_fu_831_p2 | brmerge449_demorgan_s_reg_1498);

assign tmp29_demorgan_fu_921_p2 = (phitmp_demorgan_i_fu_897_p2 | brmerge456_demorgan_s_reg_1533);

assign tmp29_fu_926_p2 = (tmp29_demorgan_fu_921_p2 ^ 1'd1);

assign tmp30_fu_943_p2 = (tmp_58_i_fu_910_p2 | brmerge456_demorgan_s_reg_1533);

assign tmp_19_fu_322_p1 = $signed(tmp_67_fu_312_p4);

assign tmp_1_i_fu_495_p1 = $signed(grp_fu_460_p2);

assign tmp_24_fu_518_p0 = reg_279;

assign tmp_28_fu_306_p2 = ((tmp_s_fu_300_p2 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_29_fu_403_p3 = ((tmp_66_fu_355_p3[0:0] === 1'b1) ? p_neg_t_fu_383_p2 : tmp_40_fu_399_p1);

assign tmp_30_fu_326_p2 = (($signed(i_cast_reg_1314) < $signed(grp_fu_262_p2)) ? 1'b1 : 1'b0);

assign tmp_32_fu_331_p1 = i_reg_194;

assign tmp_33_fu_337_p1 = grp_fu_262_p2;

assign tmp_34_fu_437_p2 = (($signed(j_assign_cast_fu_433_p1) < $signed(tmp_29_reg_1362)) ? 1'b1 : 1'b0);

assign tmp_35_fu_466_p2 = (i1_reg_239 + j_assign_cast_fu_433_p1);

assign tmp_36_fu_472_p1 = tmp_35_fu_466_p2;

assign tmp_37_fu_478_p2 = ($signed(tmp_29_reg_1362) + $signed(tmp_35_fu_466_p2));

assign tmp_38_fu_483_p1 = $signed(tmp_37_fu_478_p2);

assign tmp_39_fu_379_p1 = p_lshr_fu_369_p4;

assign tmp_39_i_fu_1180_p2 = (p_Result_24_fu_1172_p3 ^ 1'd1);

assign tmp_40_fu_399_p1 = p_lshr_f_fu_389_p4;

assign tmp_41_i_fu_1260_p2 = (p_Result_26_fu_1252_p3 ^ 1'd1);

assign tmp_42_i_cast_cast_fu_515_p1 = $signed(w_imag_V_reg_1434);

assign tmp_46_i_cast_fu_596_p1 = tmp_73_fu_588_p3;

assign tmp_50_i_fu_831_p2 = (p_Result_s_reg_1469 ^ 1'd1);

assign tmp_52_i_fu_708_p2 = (tmp_79_reg_1459 + tmp_80_reg_1464);

assign tmp_54_i_cast_fu_728_p1 = tmp_83_fu_720_p3;

assign tmp_58_i_fu_910_p2 = (p_Result_16_reg_1504 ^ 1'd1);

assign tmp_59_i_fu_1010_p2 = (p_Result_20_fu_1002_p3 ^ 1'd1);

assign tmp_61_i_fu_1099_p2 = (p_Result_22_fu_1091_p3 ^ 1'd1);

assign tmp_66_fu_355_p3 = len_assign_reg_227[32'd31];

assign tmp_67_fu_312_p4 = {{bit_reg_206[29:1]}};

assign tmp_68_fu_411_p4 = {{i1_reg_239[31:6]}};

assign tmp_70_fu_448_p1 = j_assign_reg_251[25:0];

assign tmp_73_fu_588_p3 = ret_V_fu_558_p2[32'd11];

assign tmp_74_fu_606_p3 = p_Val2_21_fu_600_p2[32'd31];

assign tmp_77_fu_642_p3 = ret_V_fu_558_p2[32'd44];

assign tmp_78_fu_546_p1 = r_V_4_fu_540_p2[44:0];

assign tmp_79_fu_550_p1 = r_V_4_fu_540_p2[31:0];

assign tmp_80_fu_554_p1 = r_V_fu_534_p2[31:0];

assign tmp_83_fu_720_p3 = tmp_52_i_fu_708_p2[32'd11];

assign tmp_84_fu_738_p3 = p_Val2_2_fu_732_p2[32'd31];

assign tmp_87_fu_774_p3 = ret_V_6_fu_686_p2[32'd44];

assign tmp_fu_349_p2 = (($signed(len_assign_reg_227) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign tmp_s_fu_300_p2 = (j_1_reg_217 & bit_cast_fu_295_p1);

assign underflow_10_fu_1266_p2 = (tmp_41_i_fu_1260_p2 & p_Result_25_fu_1240_p3);

assign underflow_2_not_i_fu_948_p2 = (tmp30_fu_943_p2 | phitmp_demorgan_i_fu_897_p2);

assign underflow_6_fu_932_p2 = (tmp29_fu_926_p2 & p_Result_16_reg_1504);

assign underflow_7_fu_1016_p2 = (tmp_59_i_fu_1010_p2 & p_Result_19_fu_989_p3);

assign underflow_8_fu_1105_p2 = (tmp_61_i_fu_1099_p2 & p_Result_21_fu_1078_p3);

assign underflow_9_fu_1186_p2 = (tmp_39_i_fu_1180_p2 & p_Result_23_fu_1160_p3);

assign underflow_fu_853_p2 = (tmp27_fu_847_p2 & p_Result_s_reg_1469);

assign underflow_not_i_fu_869_p2 = (tmp28_fu_864_p2 | phitmp446_demorgan_s_fu_818_p2);

always @ (posedge ap_clk) begin
    i_cast_reg_1314[31:7] <= 25'b0000000000000000000000000;
    len_assign_reg_227[0] <= 1'b0;
end

endmodule //fft1d_fixed
