-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft2d_fixed_top_fft2d_fixed_top_Outline_VITIS_LOOP_189_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    row_buffer_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    row_buffer_real_ce0 : OUT STD_LOGIC;
    row_buffer_real_we0 : OUT STD_LOGIC;
    row_buffer_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    row_buffer_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    row_buffer_real_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    row_buffer_real_ce1 : OUT STD_LOGIC;
    row_buffer_real_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    row_buffer_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    row_buffer_imag_ce0 : OUT STD_LOGIC;
    row_buffer_imag_we0 : OUT STD_LOGIC;
    row_buffer_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    row_buffer_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    row_buffer_imag_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    row_buffer_imag_ce1 : OUT STD_LOGIC;
    row_buffer_imag_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    matrix_real_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    matrix_real_ce0 : OUT STD_LOGIC;
    matrix_real_we0 : OUT STD_LOGIC;
    matrix_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    matrix_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    matrix_imag_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    matrix_imag_ce0 : OUT STD_LOGIC;
    matrix_imag_we0 : OUT STD_LOGIC;
    matrix_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    matrix_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_480_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_480_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    grp_fu_480_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
    grp_fu_480_p_ce : OUT STD_LOGIC;
    grp_fu_484_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_484_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    grp_fu_484_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
    grp_fu_484_p_ce : OUT STD_LOGIC;
    grp_fu_488_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_488_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    grp_fu_488_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
    grp_fu_488_p_ce : OUT STD_LOGIC;
    grp_fu_492_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_492_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    grp_fu_492_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
    grp_fu_492_p_ce : OUT STD_LOGIC );
end;


architecture behav of fft2d_fixed_top_fft2d_fixed_top_Outline_VITIS_LOOP_189_4 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln189_fu_117_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln189_reg_175 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_3_fu_123_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_reg_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln190_fu_137_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln190_reg_188 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_fu_152_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_reg_193 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_idle : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_ready : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_ap_start : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_ap_done : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_ap_idle : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_ap_ready : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_data_real_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_fu_78_data_real_ce0 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_data_real_we0 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_data_real_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_fu_78_data_real_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_fu_78_data_real_ce1 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_data_imag_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_fu_78_data_imag_ce0 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_data_imag_we0 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_data_imag_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_fu_78_data_imag_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_fu_78_data_imag_ce1 : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_grp_fu_199_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_199_p_din1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_199_p_ce : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_grp_fu_203_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_203_p_din1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_203_p_ce : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_grp_fu_207_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_207_p_din1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_207_p_ce : STD_LOGIC;
    signal grp_fft1d_fixed_fu_78_grp_fu_211_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_211_p_din1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft1d_fixed_fu_78_grp_fu_211_p_ce : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_idle : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_ready : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0 : STD_LOGIC;
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_1_reg_54 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln189_fu_111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln190_fu_131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fft1d_fixed_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ch_fu_50 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal zext_ln192_fu_143_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln192_fu_147_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_199_ce : STD_LOGIC;
    signal grp_fu_203_ce : STD_LOGIC;
    signal grp_fu_207_ce : STD_LOGIC;
    signal grp_fu_211_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (13 downto 0);
        row_buffer_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        row_buffer_real_ce0 : OUT STD_LOGIC;
        row_buffer_real_we0 : OUT STD_LOGIC;
        row_buffer_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        row_buffer_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        row_buffer_imag_ce0 : OUT STD_LOGIC;
        row_buffer_imag_we0 : OUT STD_LOGIC;
        row_buffer_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        matrix_real_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        matrix_real_ce0 : OUT STD_LOGIC;
        matrix_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        matrix_imag_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        matrix_imag_ce0 : OUT STD_LOGIC;
        matrix_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft2d_fixed_top_fft1d_fixed IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_real_ce0 : OUT STD_LOGIC;
        data_real_we0 : OUT STD_LOGIC;
        data_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        data_real_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_real_ce1 : OUT STD_LOGIC;
        data_real_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        data_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_imag_ce0 : OUT STD_LOGIC;
        data_imag_we0 : OUT STD_LOGIC;
        data_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        data_imag_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_imag_ce1 : OUT STD_LOGIC;
        data_imag_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_199_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_199_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        grp_fu_199_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
        grp_fu_199_p_ce : OUT STD_LOGIC;
        grp_fu_203_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_203_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        grp_fu_203_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
        grp_fu_203_p_ce : OUT STD_LOGIC;
        grp_fu_207_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_207_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        grp_fu_207_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
        grp_fu_207_p_ce : OUT STD_LOGIC;
        grp_fu_211_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_211_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        grp_fu_211_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
        grp_fu_211_p_ce : OUT STD_LOGIC );
    end component;


    component fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (13 downto 0);
        row_buffer_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        row_buffer_real_ce0 : OUT STD_LOGIC;
        row_buffer_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        row_buffer_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        row_buffer_imag_ce0 : OUT STD_LOGIC;
        row_buffer_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        matrix_real_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        matrix_real_ce0 : OUT STD_LOGIC;
        matrix_real_we0 : OUT STD_LOGIC;
        matrix_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        matrix_imag_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        matrix_imag_ce0 : OUT STD_LOGIC;
        matrix_imag_we0 : OUT STD_LOGIC;
        matrix_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft2d_fixed_top_mul_32s_13s_45_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component fft2d_fixed_top_mul_32s_14s_44_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;



begin
    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65 : component fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start,
        ap_done => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done,
        ap_idle => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_idle,
        ap_ready => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_ready,
        empty => tmp_reg_193,
        row_buffer_real_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0,
        row_buffer_real_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0,
        row_buffer_real_we0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0,
        row_buffer_real_d0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0,
        row_buffer_imag_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0,
        row_buffer_imag_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0,
        row_buffer_imag_we0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0,
        row_buffer_imag_d0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0,
        matrix_real_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0,
        matrix_real_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0,
        matrix_real_q0 => matrix_real_q0,
        matrix_imag_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0,
        matrix_imag_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0,
        matrix_imag_q0 => matrix_imag_q0);

    grp_fft1d_fixed_fu_78 : component fft2d_fixed_top_fft1d_fixed
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft1d_fixed_fu_78_ap_start,
        ap_done => grp_fft1d_fixed_fu_78_ap_done,
        ap_idle => grp_fft1d_fixed_fu_78_ap_idle,
        ap_ready => grp_fft1d_fixed_fu_78_ap_ready,
        data_real_address0 => grp_fft1d_fixed_fu_78_data_real_address0,
        data_real_ce0 => grp_fft1d_fixed_fu_78_data_real_ce0,
        data_real_we0 => grp_fft1d_fixed_fu_78_data_real_we0,
        data_real_d0 => grp_fft1d_fixed_fu_78_data_real_d0,
        data_real_q0 => row_buffer_real_q0,
        data_real_address1 => grp_fft1d_fixed_fu_78_data_real_address1,
        data_real_ce1 => grp_fft1d_fixed_fu_78_data_real_ce1,
        data_real_q1 => row_buffer_real_q1,
        data_imag_address0 => grp_fft1d_fixed_fu_78_data_imag_address0,
        data_imag_ce0 => grp_fft1d_fixed_fu_78_data_imag_ce0,
        data_imag_we0 => grp_fft1d_fixed_fu_78_data_imag_we0,
        data_imag_d0 => grp_fft1d_fixed_fu_78_data_imag_d0,
        data_imag_q0 => row_buffer_imag_q0,
        data_imag_address1 => grp_fft1d_fixed_fu_78_data_imag_address1,
        data_imag_ce1 => grp_fft1d_fixed_fu_78_data_imag_ce1,
        data_imag_q1 => row_buffer_imag_q1,
        grp_fu_199_p_din0 => grp_fft1d_fixed_fu_78_grp_fu_199_p_din0,
        grp_fu_199_p_din1 => grp_fft1d_fixed_fu_78_grp_fu_199_p_din1,
        grp_fu_199_p_dout0 => grp_fu_480_p_dout0,
        grp_fu_199_p_ce => grp_fft1d_fixed_fu_78_grp_fu_199_p_ce,
        grp_fu_203_p_din0 => grp_fft1d_fixed_fu_78_grp_fu_203_p_din0,
        grp_fu_203_p_din1 => grp_fft1d_fixed_fu_78_grp_fu_203_p_din1,
        grp_fu_203_p_dout0 => grp_fu_484_p_dout0,
        grp_fu_203_p_ce => grp_fft1d_fixed_fu_78_grp_fu_203_p_ce,
        grp_fu_207_p_din0 => grp_fft1d_fixed_fu_78_grp_fu_207_p_din0,
        grp_fu_207_p_din1 => grp_fft1d_fixed_fu_78_grp_fu_207_p_din1,
        grp_fu_207_p_dout0 => grp_fu_488_p_dout0,
        grp_fu_207_p_ce => grp_fft1d_fixed_fu_78_grp_fu_207_p_ce,
        grp_fu_211_p_din0 => grp_fft1d_fixed_fu_78_grp_fu_211_p_din0,
        grp_fu_211_p_din1 => grp_fft1d_fixed_fu_78_grp_fu_211_p_din1,
        grp_fu_211_p_dout0 => grp_fu_492_p_dout0,
        grp_fu_211_p_ce => grp_fft1d_fixed_fu_78_grp_fu_211_p_ce);

    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90 : component fft2d_fixed_top_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start,
        ap_done => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done,
        ap_idle => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_idle,
        ap_ready => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_ready,
        empty => tmp_reg_193,
        row_buffer_real_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0,
        row_buffer_real_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0,
        row_buffer_real_q0 => row_buffer_real_q0,
        row_buffer_imag_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0,
        row_buffer_imag_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0,
        row_buffer_imag_q0 => row_buffer_imag_q0,
        matrix_real_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0,
        matrix_real_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0,
        matrix_real_we0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0,
        matrix_real_d0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_d0,
        matrix_imag_address0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0,
        matrix_imag_ce0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0,
        matrix_imag_we0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0,
        matrix_imag_d0 => grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fft1d_fixed_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft1d_fixed_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_fft1d_fixed_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft1d_fixed_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_fft1d_fixed_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln190_fu_131_p2 = ap_const_lv1_0))) then 
                    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_ready = ap_const_logic_1)) then 
                    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_ready = ap_const_logic_1)) then 
                    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ch_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ch_fu_50 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln190_fu_131_p2 = ap_const_lv1_1))) then 
                ch_fu_50 <= add_ln189_reg_175;
            end if; 
        end if;
    end process;

    r_1_reg_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done = ap_const_logic_1))) then 
                r_1_reg_54 <= add_ln190_reg_188;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln189_fu_111_p2 = ap_const_lv1_0))) then 
                r_1_reg_54 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln189_reg_175 <= add_ln189_fu_117_p2;
                    tmp_3_reg_180(7 downto 6) <= tmp_3_fu_123_p3(7 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln190_reg_188 <= add_ln190_fu_137_p2;
                    tmp_reg_193(13 downto 6) <= tmp_fu_152_p3(13 downto 6);
            end if;
        end if;
    end process;
    tmp_3_reg_180(5 downto 0) <= "000000";
    tmp_reg_193(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done, grp_fft1d_fixed_fu_78_ap_done, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done, icmp_ln189_fu_111_p2, ap_CS_fsm_state8, icmp_ln190_fu_131_p2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln189_fu_111_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln190_fu_131_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_fft1d_fixed_fu_78_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln189_fu_117_p2 <= std_logic_vector(unsigned(ch_fu_50) + unsigned(ap_const_lv2_1));
    add_ln190_fu_137_p2 <= std_logic_vector(unsigned(r_1_reg_54) + unsigned(ap_const_lv7_1));
    add_ln192_fu_147_p2 <= std_logic_vector(unsigned(tmp_3_reg_180) + unsigned(zext_ln192_fu_143_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done)
    begin
        if ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_fft1d_fixed_fu_78_ap_done)
    begin
        if ((grp_fft1d_fixed_fu_78_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done)
    begin
        if ((grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln189_fu_111_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln189_fu_111_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln189_fu_111_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln189_fu_111_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fft1d_fixed_fu_78_ap_start <= grp_fft1d_fixed_fu_78_ap_start_reg;
    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_ap_start_reg;
    grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_ap_start_reg;

    grp_fu_199_ce_assign_proc : process(grp_fft1d_fixed_fu_78_grp_fu_199_p_ce, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_199_ce <= grp_fft1d_fixed_fu_78_grp_fu_199_p_ce;
        else 
            grp_fu_199_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_203_ce_assign_proc : process(grp_fft1d_fixed_fu_78_grp_fu_203_p_ce, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_203_ce <= grp_fft1d_fixed_fu_78_grp_fu_203_p_ce;
        else 
            grp_fu_203_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_207_ce_assign_proc : process(grp_fft1d_fixed_fu_78_grp_fu_207_p_ce, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_207_ce <= grp_fft1d_fixed_fu_78_grp_fu_207_p_ce;
        else 
            grp_fu_207_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_211_ce_assign_proc : process(grp_fft1d_fixed_fu_78_grp_fu_211_p_ce, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_211_ce <= grp_fft1d_fixed_fu_78_grp_fu_211_p_ce;
        else 
            grp_fu_211_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_480_p_ce <= grp_fu_199_ce;
    grp_fu_480_p_din0 <= grp_fft1d_fixed_fu_78_grp_fu_199_p_din0;
    grp_fu_480_p_din1 <= grp_fft1d_fixed_fu_78_grp_fu_199_p_din1;
    grp_fu_484_p_ce <= grp_fu_203_ce;
    grp_fu_484_p_din0 <= grp_fft1d_fixed_fu_78_grp_fu_203_p_din0;
    grp_fu_484_p_din1 <= grp_fft1d_fixed_fu_78_grp_fu_203_p_din1;
    grp_fu_488_p_ce <= grp_fu_207_ce;
    grp_fu_488_p_din0 <= grp_fft1d_fixed_fu_78_grp_fu_207_p_din0;
    grp_fu_488_p_din1 <= grp_fft1d_fixed_fu_78_grp_fu_207_p_din1;
    grp_fu_492_p_ce <= grp_fu_211_ce;
    grp_fu_492_p_din0 <= grp_fft1d_fixed_fu_78_grp_fu_211_p_din0;
    grp_fu_492_p_din1 <= grp_fft1d_fixed_fu_78_grp_fu_211_p_din1;
    icmp_ln189_fu_111_p2 <= "1" when (ch_fu_50 = ap_const_lv2_3) else "0";
    icmp_ln190_fu_131_p2 <= "1" when (r_1_reg_54 = ap_const_lv7_40) else "0";

    matrix_imag_address0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0, ap_CS_fsm_state8, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrix_imag_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            matrix_imag_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_address0;
        else 
            matrix_imag_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    matrix_imag_ce0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0, ap_CS_fsm_state8, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrix_imag_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            matrix_imag_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_imag_ce0;
        else 
            matrix_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_imag_d0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_d0;

    matrix_imag_we0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrix_imag_we0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_imag_we0;
        else 
            matrix_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;


    matrix_real_address0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0, ap_CS_fsm_state8, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrix_real_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            matrix_real_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_address0;
        else 
            matrix_real_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    matrix_real_ce0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0, ap_CS_fsm_state8, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrix_real_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            matrix_real_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_matrix_real_ce0;
        else 
            matrix_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_real_d0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_d0;

    matrix_real_we0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrix_real_we0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_matrix_real_we0;
        else 
            matrix_real_we0 <= ap_const_logic_0;
        end if; 
    end process;


    row_buffer_imag_address0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0, grp_fft1d_fixed_fu_78_data_imag_address0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0, ap_CS_fsm_state8, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            row_buffer_imag_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_imag_address0 <= grp_fft1d_fixed_fu_78_data_imag_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_imag_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_address0;
        else 
            row_buffer_imag_address0 <= "XXXXXX";
        end if; 
    end process;

    row_buffer_imag_address1 <= grp_fft1d_fixed_fu_78_data_imag_address1;

    row_buffer_imag_ce0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0, grp_fft1d_fixed_fu_78_data_imag_ce0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0, ap_CS_fsm_state8, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            row_buffer_imag_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_imag_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_imag_ce0 <= grp_fft1d_fixed_fu_78_data_imag_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_imag_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_ce0;
        else 
            row_buffer_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    row_buffer_imag_ce1_assign_proc : process(grp_fft1d_fixed_fu_78_data_imag_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_imag_ce1 <= grp_fft1d_fixed_fu_78_data_imag_ce1;
        else 
            row_buffer_imag_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    row_buffer_imag_d0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0, grp_fft1d_fixed_fu_78_data_imag_d0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_imag_d0 <= grp_fft1d_fixed_fu_78_data_imag_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_imag_d0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_d0;
        else 
            row_buffer_imag_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    row_buffer_imag_we0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0, grp_fft1d_fixed_fu_78_data_imag_we0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_imag_we0 <= grp_fft1d_fixed_fu_78_data_imag_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_imag_we0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_imag_we0;
        else 
            row_buffer_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;


    row_buffer_real_address0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0, grp_fft1d_fixed_fu_78_data_real_address0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0, ap_CS_fsm_state8, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            row_buffer_real_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_real_address0 <= grp_fft1d_fixed_fu_78_data_real_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_real_address0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_address0;
        else 
            row_buffer_real_address0 <= "XXXXXX";
        end if; 
    end process;

    row_buffer_real_address1 <= grp_fft1d_fixed_fu_78_data_real_address1;

    row_buffer_real_ce0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0, grp_fft1d_fixed_fu_78_data_real_ce0, grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0, ap_CS_fsm_state8, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            row_buffer_real_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_197_7_fu_90_row_buffer_real_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_real_ce0 <= grp_fft1d_fixed_fu_78_data_real_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_real_ce0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_ce0;
        else 
            row_buffer_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    row_buffer_real_ce1_assign_proc : process(grp_fft1d_fixed_fu_78_data_real_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_real_ce1 <= grp_fft1d_fixed_fu_78_data_real_ce1;
        else 
            row_buffer_real_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    row_buffer_real_d0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0, grp_fft1d_fixed_fu_78_data_real_d0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_real_d0 <= grp_fft1d_fixed_fu_78_data_real_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_real_d0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_d0;
        else 
            row_buffer_real_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    row_buffer_real_we0_assign_proc : process(grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0, grp_fft1d_fixed_fu_78_data_real_we0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_buffer_real_we0 <= grp_fft1d_fixed_fu_78_data_real_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_buffer_real_we0 <= grp_fft2d_fixed_top_Pipeline_VITIS_LOOP_191_6_fu_65_row_buffer_real_we0;
        else 
            row_buffer_real_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_3_fu_123_p3 <= (ch_fu_50 & ap_const_lv6_0);
    tmp_fu_152_p3 <= (add_ln192_fu_147_p2 & ap_const_lv6_0);
    zext_ln192_fu_143_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_1_reg_54),8));
end behav;
