-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fft2d_fixed_top_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_TWIDDLE_IMAG_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 13; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of fft2d_fixed_top_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_TWIDDLE_IMAG_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000000000000", 1 => "1111001101111", 2 => "1110011100001", 3 => "1101101011011", 
    4 => "1100111100001", 5 => "1100001110101", 6 => "1011100011100", 7 => "1010111011010", 
    8 => "1010010110000", 9 => "1001110100010", 10 => "1001010110010", 11 => "1000111100100", 
    12 => "1000100111000", 13 => "1000010110000", 14 => "1000001001111", 15 => "1000000010100", 
    16 => "1000000000000", 17 => "1000000010100", 18 => "1000001001111", 19 => "1000010110000", 
    20 => "1000100111000", 21 => "1000111100100", 22 => "1001010110010", 23 => "1001110100010", 
    24 => "1010010110000", 25 => "1010111011010", 26 => "1011100011100", 27 => "1100001110101", 
    28 => "1100111100001", 29 => "1101101011011", 30 => "1110011100001", 31 => "1111001101111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

