-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft1d_fixed is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_real_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_real_V_ce0 : OUT STD_LOGIC;
    data_real_V_we0 : OUT STD_LOGIC;
    data_real_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_real_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_real_V_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_real_V_ce1 : OUT STD_LOGIC;
    data_real_V_we1 : OUT STD_LOGIC;
    data_real_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_real_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_imag_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_imag_V_ce0 : OUT STD_LOGIC;
    data_imag_V_we0 : OUT STD_LOGIC;
    data_imag_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_imag_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_imag_V_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_imag_V_ce1 : OUT STD_LOGIC;
    data_imag_V_we1 : OUT STD_LOGIC;
    data_imag_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_imag_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of fft1d_fixed is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (48 downto 0) := "0000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (48 downto 0) := "0000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (48 downto 0) := "0000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (48 downto 0) := "0000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (48 downto 0) := "0000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (48 downto 0) := "0000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (48 downto 0) := "0001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (48 downto 0) := "0010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (48 downto 0) := "0100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (48 downto 0) := "1000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv30_20 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000100000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv26_1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal TWIDDLE_REAL_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal TWIDDLE_REAL_V_ce0 : STD_LOGIC;
    signal TWIDDLE_REAL_V_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal TWIDDLE_IMAG_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal TWIDDLE_IMAG_V_ce0 : STD_LOGIC;
    signal TWIDDLE_IMAG_V_q0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_267 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_28_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_273 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state44 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state44 : signal is "none";
    signal ap_CS_fsm_state47 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state47 : signal is "none";
    signal reg_279 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_cast_fu_285_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_cast_reg_1314 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_19_fu_322_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_30_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_reg_1330 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_real_V_addr_reg_1334 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_V_addr_reg_1339 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_real_V_addr_4_reg_1344 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_V_addr_4_reg_1349 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_3_fu_343_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_29_fu_403_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_reg_1362 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal len_fu_427_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_7_fu_442_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal j_7_reg_1379 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_34_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_real_V_addr_5_reg_1389 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_V_addr_5_reg_1395 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_real_V_addr_6_reg_1401 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_V_addr_6_reg_1407 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_4_fu_489_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state43 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state43 : signal is "none";
    signal w_real_V_reg_1428 : STD_LOGIC_VECTOR (13 downto 0);
    signal w_imag_V_reg_1434 : STD_LOGIC_VECTOR (12 downto 0);
    signal lhs_V_i_cast_fu_522_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal lhs_V_i_cast_reg_1439 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_CS_fsm_state45 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state45 : signal is "none";
    signal rhs_V_i_cast_fu_528_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal rhs_V_i_cast_reg_1444 : STD_LOGIC_VECTOR (44 downto 0);
    signal r_V_fu_534_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal r_V_reg_1449 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_78_fu_546_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_78_reg_1454 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_79_fu_550_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_79_reg_1459 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_80_fu_554_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_80_reg_1464 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_reg_1469 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state46 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state46 : signal is "none";
    signal p_Val2_21_fu_600_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_21_reg_1475 : STD_LOGIC_VECTOR (31 downto 0);
    signal carry_4_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_4_reg_1481 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_626_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_reg_1487 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_reg_1492 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge449_demorgan_s_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge449_demorgan_s_reg_1498 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_16_reg_1504 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_2_fu_732_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_2_reg_1510 : STD_LOGIC_VECTOR (31 downto 0);
    signal carry_6_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_6_reg_1516 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_18_fu_758_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_18_reg_1522 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_2_fu_766_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_2_reg_1527 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge456_demorgan_s_fu_812_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge456_demorgan_s_reg_1533 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_26_fu_889_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_26_reg_1539 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_30_fu_968_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_30_reg_1545 : STD_LOGIC_VECTOR (31 downto 0);
    signal ComplexFixed_real_V_2_fu_1226_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ComplexFixed_real_V_2_reg_1551 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state48 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state48 : signal is "none";
    signal ComplexFixed_imag_V_2_fu_1306_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ComplexFixed_imag_V_2_reg_1556 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_reg_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_194 : STD_LOGIC_VECTOR (6 downto 0);
    signal bit_reg_206 : STD_LOGIC_VECTOR (29 downto 0);
    signal exitcond_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_1_reg_217 : STD_LOGIC_VECTOR (31 downto 0);
    signal len_assign_reg_227 : STD_LOGIC_VECTOR (31 downto 0);
    signal i1_reg_239 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_assign_reg_251 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state49 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state49 : signal is "none";
    signal tmp_32_fu_331_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_33_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_36_fu_472_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_38_fu_483_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_i_fu_495_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ComplexFixed_real_V_s_fu_1056_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ComplexFixed_imag_V_s_fu_1145_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bit_cast_fu_295_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_67_fu_312_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_neg_fu_363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_fu_369_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_39_fu_379_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_lshr_f_fu_389_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_66_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t_fu_383_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_40_fu_399_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_68_fu_411_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal j_assign_cast_fu_433_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_70_fu_448_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_460_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_35_fu_466_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_37_fu_478_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_460_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_i_cast_cast_fu_501_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_i_cast_cast_fu_511_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_518_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_i_cast_fu_522_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_i_cast_cast_fu_501_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal lhs_V_i_cast_fu_522_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal rhs_V_i_cast_fu_528_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_V_i_cast_fu_528_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_42_i_cast_cast_fu_515_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal r_V_fu_534_p0 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_fu_534_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_fu_540_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_fu_540_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_4_fu_540_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal ret_V_fu_558_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_73_fu_588_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_20_fu_570_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_46_i_cast_fu_596_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_74_fu_606_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_14_fu_580_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_642_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_4_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev4_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_i_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_6_fu_686_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_52_i_fu_708_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_83_fu_720_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_i_cast_fu_728_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_1_fu_698_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_84_fu_738_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_17_fu_712_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev5_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_87_fu_774_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not2_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_6_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev6_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_3_i_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_6_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_i_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp446_demorgan_s_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp27_demorgan_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp27_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_853_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp28_fu_864_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_i_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_not_i_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_11_mux_i_fu_875_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_i_fu_882_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_not1_i_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge6_i_fu_905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_i_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp_demorgan_i_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp29_demorgan_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp29_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_6_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_2_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp30_fu_943_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge8_i_fu_937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_not_i_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_16_mux_i_fu_954_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_1_i_fu_961_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_fu_976_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_fu_976_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal rhs_V_fu_980_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_7_fu_983_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Val2_28_fu_997_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_28_fu_997_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_20_fu_1002_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_19_fu_989_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_i_fu_1010_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_not_i_fu_1028_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge9_i_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_7_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge3_i_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_19_mux_i_fu_1040_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_i7_fu_1048_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_2_fu_1065_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_V_2_fu_1065_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal rhs_V_2_fu_1069_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_8_fu_1072_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Val2_32_fu_1086_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_32_fu_1086_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_22_fu_1091_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_21_fu_1078_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_i_fu_1099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_14_not_i_fu_1117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge2_i_fu_1111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_8_fu_1105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge4_i9_fu_1123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_23_mux_i_fu_1129_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_2_i_fu_1137_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_9_fu_1154_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Result_24_fu_1172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_1160_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_i_fu_1180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_not_i2_fu_1198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge1_i_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_34_fu_1168_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal underflow_9_fu_1186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge4_i_fu_1204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_3_mux_i_fu_1210_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_3_i_fu_1218_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_10_fu_1234_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Result_26_fu_1252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_25_fu_1240_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_i_fu_1260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_not_i_fu_1278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge3_i2_fu_1272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_36_fu_1248_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal underflow_10_fu_1266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_i2_fu_1284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_7_mux_i_fu_1290_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_7_i_fu_1298_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_460_ap_start : STD_LOGIC;
    signal grp_fu_460_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (48 downto 0);

    component fft2d_fixed_top_sdEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft1d_fixed_TWIDDbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component fft1d_fixed_TWIDDcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;



begin
    TWIDDLE_REAL_V_U : component fft1d_fixed_TWIDDbkb
    generic map (
        DataWidth => 14,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => TWIDDLE_REAL_V_address0,
        ce0 => TWIDDLE_REAL_V_ce0,
        q0 => TWIDDLE_REAL_V_q0);

    TWIDDLE_IMAG_V_U : component fft1d_fixed_TWIDDcud
    generic map (
        DataWidth => 13,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => TWIDDLE_IMAG_V_address0,
        ce0 => TWIDDLE_IMAG_V_ce0,
        q0 => TWIDDLE_IMAG_V_q0);

    fft2d_fixed_top_sdEe_U1 : component fft2d_fixed_top_sdEe
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_460_ap_start,
        done => grp_fu_460_ap_done,
        din0 => grp_fu_460_p0,
        din1 => len_assign_reg_227,
        ce => ap_const_logic_1,
        dout => grp_fu_460_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    bit_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_289_p2 = ap_const_lv1_0))) then 
                bit_reg_206 <= ap_const_lv30_20;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_28_fu_306_p2 = ap_const_lv1_0))) then 
                bit_reg_206 <= tmp_19_fu_322_p1;
            end if; 
        end if;
    end process;

    i1_reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (tmp_34_fu_437_p2 = ap_const_lv1_0))) then 
                i1_reg_239 <= i_4_fu_489_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (tmp_fu_349_p2 = ap_const_lv1_0))) then 
                i1_reg_239 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i_reg_194 <= i_3_fu_343_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_194 <= ap_const_lv7_1;
            end if; 
        end if;
    end process;

    j_1_reg_217_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_289_p2 = ap_const_lv1_0))) then 
                j_1_reg_217 <= j_reg_182;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_28_fu_306_p2 = ap_const_lv1_0))) then 
                j_1_reg_217 <= grp_fu_262_p2;
            end if; 
        end if;
    end process;

    j_assign_reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_fu_421_p2 = ap_const_lv1_1))) then 
                j_assign_reg_251 <= ap_const_lv31_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
                j_assign_reg_251 <= j_7_reg_1379;
            end if; 
        end if;
    end process;

    j_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                j_reg_182 <= reg_267;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_reg_182 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    len_assign_reg_227_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_289_p2 = ap_const_lv1_1))) then 
                len_assign_reg_227(1) <= '1';
                len_assign_reg_227(2) <= '0';
                len_assign_reg_227(3) <= '0';
                len_assign_reg_227(4) <= '0';
                len_assign_reg_227(5) <= '0';
                len_assign_reg_227(6) <= '0';
                len_assign_reg_227(7) <= '0';
                len_assign_reg_227(8) <= '0';
                len_assign_reg_227(9) <= '0';
                len_assign_reg_227(10) <= '0';
                len_assign_reg_227(11) <= '0';
                len_assign_reg_227(12) <= '0';
                len_assign_reg_227(13) <= '0';
                len_assign_reg_227(14) <= '0';
                len_assign_reg_227(15) <= '0';
                len_assign_reg_227(16) <= '0';
                len_assign_reg_227(17) <= '0';
                len_assign_reg_227(18) <= '0';
                len_assign_reg_227(19) <= '0';
                len_assign_reg_227(20) <= '0';
                len_assign_reg_227(21) <= '0';
                len_assign_reg_227(22) <= '0';
                len_assign_reg_227(23) <= '0';
                len_assign_reg_227(24) <= '0';
                len_assign_reg_227(25) <= '0';
                len_assign_reg_227(26) <= '0';
                len_assign_reg_227(27) <= '0';
                len_assign_reg_227(28) <= '0';
                len_assign_reg_227(29) <= '0';
                len_assign_reg_227(30) <= '0';
                len_assign_reg_227(31) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_fu_421_p2 = ap_const_lv1_0))) then 
                                len_assign_reg_227(31 downto 1) <= len_fu_427_p2(31 downto 1);
            end if; 
        end if;
    end process;

    reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state47)) then 
                reg_273 <= data_real_V_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state44) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                reg_273 <= data_real_V_q0;
            end if; 
        end if;
    end process;

    reg_279_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state47)) then 
                reg_279 <= data_imag_V_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state44) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                reg_279 <= data_imag_V_q0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state48)) then
                ComplexFixed_imag_V_2_reg_1556 <= ComplexFixed_imag_V_2_fu_1306_p3;
                ComplexFixed_real_V_2_reg_1551 <= ComplexFixed_real_V_2_fu_1226_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state46)) then
                Range2_all_ones_2_reg_1527 <= ret_V_6_fu_686_p2(44 downto 44);
                Range2_all_ones_reg_1492 <= ret_V_fu_558_p2(44 downto 44);
                brmerge449_demorgan_s_reg_1498 <= brmerge449_demorgan_s_fu_680_p2;
                brmerge456_demorgan_s_reg_1533 <= brmerge456_demorgan_s_fu_812_p2;
                carry_4_reg_1481 <= carry_4_fu_620_p2;
                carry_6_reg_1516 <= carry_6_fu_752_p2;
                p_Result_15_reg_1487 <= p_Val2_21_fu_600_p2(31 downto 31);
                p_Result_16_reg_1504 <= ret_V_6_fu_686_p2(44 downto 44);
                p_Result_18_reg_1522 <= p_Val2_2_fu_732_p2(31 downto 31);
                p_Result_s_reg_1469 <= ret_V_fu_558_p2(44 downto 44);
                p_Val2_21_reg_1475 <= p_Val2_21_fu_600_p2;
                p_Val2_2_reg_1510 <= p_Val2_2_fu_732_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_30_fu_326_p2 = ap_const_lv1_1) and (tmp_28_fu_306_p2 = ap_const_lv1_1))) then
                data_imag_V_addr_4_reg_1349 <= tmp_33_fu_337_p1(6 - 1 downto 0);
                data_imag_V_addr_reg_1339 <= tmp_32_fu_331_p1(6 - 1 downto 0);
                data_real_V_addr_4_reg_1344 <= tmp_33_fu_337_p1(6 - 1 downto 0);
                data_real_V_addr_reg_1334 <= tmp_32_fu_331_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (tmp_34_fu_437_p2 = ap_const_lv1_1))) then
                data_imag_V_addr_5_reg_1395 <= tmp_36_fu_472_p1(6 - 1 downto 0);
                data_imag_V_addr_6_reg_1407 <= tmp_38_fu_483_p1(6 - 1 downto 0);
                data_real_V_addr_5_reg_1389 <= tmp_36_fu_472_p1(6 - 1 downto 0);
                data_real_V_addr_6_reg_1401 <= tmp_38_fu_483_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    i_cast_reg_1314(6 downto 0) <= i_cast_fu_285_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                j_7_reg_1379 <= j_7_fu_442_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state45)) then
                lhs_V_i_cast_reg_1439 <= lhs_V_i_cast_fu_522_p2;
                r_V_reg_1449 <= r_V_fu_534_p2;
                rhs_V_i_cast_reg_1444 <= rhs_V_i_cast_fu_528_p2;
                tmp_78_reg_1454 <= tmp_78_fu_546_p1;
                tmp_79_reg_1459 <= tmp_79_fu_550_p1;
                tmp_80_reg_1464 <= tmp_80_fu_554_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state47)) then
                p_Val2_26_reg_1539 <= p_Val2_26_fu_889_p3;
                p_Val2_30_reg_1545 <= p_Val2_30_fu_968_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_28_fu_306_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_28_fu_306_p2 = ap_const_lv1_0)))) then
                reg_267 <= grp_fu_262_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (tmp_fu_349_p2 = ap_const_lv1_0))) then
                tmp_29_reg_1362 <= tmp_29_fu_403_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_28_fu_306_p2 = ap_const_lv1_1))) then
                tmp_30_reg_1330 <= tmp_30_fu_326_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state44)) then
                w_imag_V_reg_1434 <= TWIDDLE_IMAG_V_q0;
                w_real_V_reg_1428 <= TWIDDLE_REAL_V_q0;
            end if;
        end if;
    end process;
    i_cast_reg_1314(31 downto 7) <= "0000000000000000000000000";
    len_assign_reg_227(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, tmp_28_fu_306_p2, ap_CS_fsm_state2, tmp_30_fu_326_p2, ap_CS_fsm_state6, tmp_fu_349_p2, ap_CS_fsm_state7, icmp_fu_421_p2, ap_CS_fsm_state8, tmp_34_fu_437_p2, exitcond_fu_289_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_fu_289_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_30_fu_326_p2 = ap_const_lv1_0) and (tmp_28_fu_306_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_30_fu_326_p2 = ap_const_lv1_1) and (tmp_28_fu_306_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (tmp_fu_349_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_fu_421_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (tmp_34_fu_437_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ComplexFixed_imag_V_2_fu_1306_p3 <= 
        p_Val2_7_mux_i_fu_1290_p3 when (brmerge5_i2_fu_1284_p2(0) = '1') else 
        p_Val2_7_i_fu_1298_p3;
    ComplexFixed_imag_V_s_fu_1145_p3 <= 
        p_Val2_23_mux_i_fu_1129_p3 when (brmerge4_i9_fu_1123_p2(0) = '1') else 
        p_Val2_2_i_fu_1137_p3;
    ComplexFixed_real_V_2_fu_1226_p3 <= 
        p_Val2_3_mux_i_fu_1210_p3 when (brmerge4_i_fu_1204_p2(0) = '1') else 
        p_Val2_3_i_fu_1218_p3;
    ComplexFixed_real_V_s_fu_1056_p3 <= 
        p_Val2_19_mux_i_fu_1040_p3 when (brmerge3_i_fu_1034_p2(0) = '1') else 
        p_Val2_i7_fu_1048_p3;
    Range2_all_ones_2_fu_766_p3 <= ret_V_6_fu_686_p2(44 downto 44);
    Range2_all_ones_fu_634_p3 <= ret_V_fu_558_p2(44 downto 44);
    TWIDDLE_IMAG_V_address0 <= tmp_1_i_fu_495_p1(5 - 1 downto 0);

    TWIDDLE_IMAG_V_ce0_assign_proc : process(ap_CS_fsm_state43)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state43)) then 
            TWIDDLE_IMAG_V_ce0 <= ap_const_logic_1;
        else 
            TWIDDLE_IMAG_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    TWIDDLE_REAL_V_address0 <= tmp_1_i_fu_495_p1(5 - 1 downto 0);

    TWIDDLE_REAL_V_ce0_assign_proc : process(ap_CS_fsm_state43)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state43)) then 
            TWIDDLE_REAL_V_ce0 <= ap_const_logic_1;
        else 
            TWIDDLE_REAL_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state43 <= ap_CS_fsm(42);
    ap_CS_fsm_state44 <= ap_CS_fsm(43);
    ap_CS_fsm_state45 <= ap_CS_fsm(44);
    ap_CS_fsm_state46 <= ap_CS_fsm(45);
    ap_CS_fsm_state47 <= ap_CS_fsm(46);
    ap_CS_fsm_state48 <= ap_CS_fsm(47);
    ap_CS_fsm_state49 <= ap_CS_fsm(48);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6, tmp_fu_349_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (tmp_fu_349_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, tmp_fu_349_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (tmp_fu_349_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        bit_cast_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bit_reg_206),32));

    brmerge1_i_fu_1192_p2 <= (p_Result_24_fu_1172_p3 xor p_Result_23_fu_1160_p3);
    brmerge2_i_fu_1111_p2 <= (p_Result_22_fu_1091_p3 xor p_Result_21_fu_1078_p3);
    brmerge3_i2_fu_1272_p2 <= (p_Result_26_fu_1252_p3 xor p_Result_25_fu_1240_p3);
    brmerge3_i_fu_1034_p2 <= (p_Result_not_i_fu_1028_p2 or p_Result_20_fu_1002_p3);
    brmerge449_demorgan_s_fu_680_p2 <= (p_Result_15_fu_626_p3 and deleted_ones_fu_674_p2);
    brmerge456_demorgan_s_fu_812_p2 <= (p_Result_18_fu_758_p3 and deleted_ones_6_fu_806_p2);
    brmerge4_i9_fu_1123_p2 <= (p_Result_22_fu_1091_p3 or p_Result_14_not_i_fu_1117_p2);
    brmerge4_i_fu_1204_p2 <= (p_Result_not_i2_fu_1198_p2 or p_Result_24_fu_1172_p3);
    brmerge5_i2_fu_1284_p2 <= (p_Result_2_not_i_fu_1278_p2 or p_Result_26_fu_1252_p3);
    brmerge5_i_fu_858_p2 <= (underflow_fu_853_p2 or overflow_fu_836_p2);
    brmerge6_i_fu_905_p2 <= (p_not1_i_fu_901_p2 or p_Result_18_reg_1522);
    brmerge8_i_fu_937_p2 <= (underflow_6_fu_932_p2 or overflow_2_fu_915_p2);
    brmerge9_i_fu_1022_p2 <= (p_Result_20_fu_1002_p3 xor p_Result_19_fu_989_p3);
    brmerge_i_fu_826_p2 <= (p_not_i_fu_822_p2 or p_Result_15_reg_1487);
    carry_4_fu_620_p2 <= (rev_fu_614_p2 and p_Result_14_fu_580_p3);
    carry_6_fu_752_p2 <= (rev5_fu_746_p2 and p_Result_17_fu_712_p3);

    data_imag_V_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, data_imag_V_addr_reg_1339, data_imag_V_addr_5_reg_1395, data_imag_V_addr_6_reg_1407, ap_CS_fsm_state43, ap_CS_fsm_state48, tmp_32_fu_331_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state48)) then 
            data_imag_V_address0 <= data_imag_V_addr_5_reg_1395;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state43)) then 
            data_imag_V_address0 <= data_imag_V_addr_6_reg_1407;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_imag_V_address0 <= data_imag_V_addr_reg_1339;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_imag_V_address0 <= tmp_32_fu_331_p1(6 - 1 downto 0);
        else 
            data_imag_V_address0 <= "XXXXXX";
        end if; 
    end process;


    data_imag_V_address1_assign_proc : process(ap_CS_fsm_state3, data_imag_V_addr_4_reg_1349, ap_CS_fsm_state5, data_imag_V_addr_5_reg_1395, data_imag_V_addr_6_reg_1407, ap_CS_fsm_state46, ap_CS_fsm_state49, tmp_33_fu_337_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
            data_imag_V_address1 <= data_imag_V_addr_6_reg_1407;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state46)) then 
            data_imag_V_address1 <= data_imag_V_addr_5_reg_1395;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            data_imag_V_address1 <= data_imag_V_addr_4_reg_1349;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_imag_V_address1 <= tmp_33_fu_337_p1(6 - 1 downto 0);
        else 
            data_imag_V_address1 <= "XXXXXX";
        end if; 
    end process;


    data_imag_V_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state43, ap_CS_fsm_state48)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state48) or (ap_const_logic_1 = ap_CS_fsm_state43) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_imag_V_ce0 <= ap_const_logic_1;
        else 
            data_imag_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_imag_V_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state46, ap_CS_fsm_state49)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state49) or (ap_const_logic_1 = ap_CS_fsm_state46) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_imag_V_ce1 <= ap_const_logic_1;
        else 
            data_imag_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    data_imag_V_d0_assign_proc : process(data_imag_V_q1, ap_CS_fsm_state4, ap_CS_fsm_state48, ComplexFixed_imag_V_s_fu_1145_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state48)) then 
            data_imag_V_d0 <= ComplexFixed_imag_V_s_fu_1145_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_imag_V_d0 <= data_imag_V_q1;
        else 
            data_imag_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    data_imag_V_d1_assign_proc : process(reg_279, ap_CS_fsm_state5, ComplexFixed_imag_V_2_reg_1556, ap_CS_fsm_state49)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
            data_imag_V_d1 <= ComplexFixed_imag_V_2_reg_1556;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            data_imag_V_d1 <= reg_279;
        else 
            data_imag_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    data_imag_V_we0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state48)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state48) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_imag_V_we0 <= ap_const_logic_1;
        else 
            data_imag_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    data_imag_V_we1_assign_proc : process(tmp_30_reg_1330, ap_CS_fsm_state5, ap_CS_fsm_state49)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state49) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_30_reg_1330 = ap_const_lv1_1)))) then 
            data_imag_V_we1 <= ap_const_logic_1;
        else 
            data_imag_V_we1 <= ap_const_logic_0;
        end if; 
    end process;


    data_real_V_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, data_real_V_addr_reg_1334, data_real_V_addr_5_reg_1389, data_real_V_addr_6_reg_1401, ap_CS_fsm_state43, ap_CS_fsm_state48, tmp_32_fu_331_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state48)) then 
            data_real_V_address0 <= data_real_V_addr_5_reg_1389;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state43)) then 
            data_real_V_address0 <= data_real_V_addr_6_reg_1401;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_real_V_address0 <= data_real_V_addr_reg_1334;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_real_V_address0 <= tmp_32_fu_331_p1(6 - 1 downto 0);
        else 
            data_real_V_address0 <= "XXXXXX";
        end if; 
    end process;


    data_real_V_address1_assign_proc : process(ap_CS_fsm_state3, data_real_V_addr_4_reg_1344, ap_CS_fsm_state5, data_real_V_addr_5_reg_1389, data_real_V_addr_6_reg_1401, ap_CS_fsm_state46, ap_CS_fsm_state49, tmp_33_fu_337_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
            data_real_V_address1 <= data_real_V_addr_6_reg_1401;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state46)) then 
            data_real_V_address1 <= data_real_V_addr_5_reg_1389;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            data_real_V_address1 <= data_real_V_addr_4_reg_1344;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_real_V_address1 <= tmp_33_fu_337_p1(6 - 1 downto 0);
        else 
            data_real_V_address1 <= "XXXXXX";
        end if; 
    end process;


    data_real_V_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state43, ap_CS_fsm_state48)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state48) or (ap_const_logic_1 = ap_CS_fsm_state43) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_real_V_ce0 <= ap_const_logic_1;
        else 
            data_real_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_real_V_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state46, ap_CS_fsm_state49)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state49) or (ap_const_logic_1 = ap_CS_fsm_state46) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_real_V_ce1 <= ap_const_logic_1;
        else 
            data_real_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    data_real_V_d0_assign_proc : process(data_real_V_q1, ap_CS_fsm_state4, ap_CS_fsm_state48, ComplexFixed_real_V_s_fu_1056_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state48)) then 
            data_real_V_d0 <= ComplexFixed_real_V_s_fu_1056_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_real_V_d0 <= data_real_V_q1;
        else 
            data_real_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    data_real_V_d1_assign_proc : process(reg_273, ap_CS_fsm_state5, ComplexFixed_real_V_2_reg_1551, ap_CS_fsm_state49)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
            data_real_V_d1 <= ComplexFixed_real_V_2_reg_1551;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            data_real_V_d1 <= reg_273;
        else 
            data_real_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    data_real_V_we0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state48)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state48) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_real_V_we0 <= ap_const_logic_1;
        else 
            data_real_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    data_real_V_we1_assign_proc : process(tmp_30_reg_1330, ap_CS_fsm_state5, ap_CS_fsm_state49)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state49) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_30_reg_1330 = ap_const_lv1_1)))) then 
            data_real_V_we1 <= ap_const_logic_1;
        else 
            data_real_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    deleted_ones_6_fu_806_p2 <= (p_3_i_fu_800_p2 and Range2_all_ones_2_fu_766_p3);
    deleted_ones_fu_674_p2 <= (p_i_fu_668_p2 and Range2_all_ones_fu_634_p3);
    exitcond_fu_289_p2 <= "1" when (i_reg_194 = ap_const_lv7_40) else "0";
    grp_fu_262_p2 <= (j_1_reg_217 xor bit_cast_fu_295_p1);

    grp_fu_460_ap_start_assign_proc : process(ap_CS_fsm_state8, tmp_34_fu_437_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (tmp_34_fu_437_p2 = ap_const_lv1_1))) then 
            grp_fu_460_ap_start <= ap_const_logic_1;
        else 
            grp_fu_460_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_460_p0 <= (tmp_70_fu_448_p1 & ap_const_lv6_0);
    i_3_fu_343_p2 <= std_logic_vector(unsigned(i_reg_194) + unsigned(ap_const_lv7_1));
    i_4_fu_489_p2 <= std_logic_vector(unsigned(len_assign_reg_227) + unsigned(i1_reg_239));
    i_cast_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_194),32));
    icmp_fu_421_p2 <= "1" when (signed(tmp_68_fu_411_p4) < signed(ap_const_lv26_1)) else "0";
    j_7_fu_442_p2 <= std_logic_vector(unsigned(j_assign_reg_251) + unsigned(ap_const_lv31_1));
    j_assign_cast_fu_433_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_assign_reg_251),32));
    len_fu_427_p2 <= std_logic_vector(shift_left(unsigned(len_assign_reg_227),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    lhs_V_2_fu_1065_p0 <= reg_279;
        lhs_V_2_fu_1065_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_V_2_fu_1065_p0),33));

    lhs_V_fu_976_p0 <= reg_273;
        lhs_V_fu_976_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_V_fu_976_p0),33));

    lhs_V_i_cast_fu_522_p0 <= r_V_i_cast_cast_fu_501_p1(32 - 1 downto 0);
    lhs_V_i_cast_fu_522_p1 <= w_real_V_reg_1428;
    lhs_V_i_cast_fu_522_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(lhs_V_i_cast_fu_522_p0) * signed(lhs_V_i_cast_fu_522_p1))), 45));
    not_carry_4_fu_662_p2 <= (tmp_74_fu_606_p3 or p_not_fu_656_p2);
    not_carry_6_fu_794_p2 <= (tmp_84_fu_738_p3 or p_not2_fu_788_p2);
    overflow_2_fu_915_p2 <= (tmp_58_i_fu_910_p2 and brmerge6_i_fu_905_p2);
    overflow_fu_836_p2 <= (tmp_50_i_fu_831_p2 and brmerge_i_fu_826_p2);
    p_3_i_fu_800_p2 <= (rev6_fu_782_p2 or not_carry_6_fu_794_p2);
    p_Result_14_fu_580_p3 <= ret_V_fu_558_p2(43 downto 43);
    p_Result_14_not_i_fu_1117_p2 <= (p_Result_21_fu_1078_p3 xor ap_const_lv1_1);
    p_Result_15_fu_626_p3 <= p_Val2_21_fu_600_p2(31 downto 31);
    p_Result_17_fu_712_p3 <= ret_V_6_fu_686_p2(43 downto 43);
    p_Result_18_fu_758_p3 <= p_Val2_2_fu_732_p2(31 downto 31);
    p_Result_19_fu_989_p3 <= ret_V_7_fu_983_p2(32 downto 32);
    p_Result_20_fu_1002_p3 <= p_Val2_28_fu_997_p2(31 downto 31);
    p_Result_21_fu_1078_p3 <= ret_V_8_fu_1072_p2(32 downto 32);
    p_Result_22_fu_1091_p3 <= p_Val2_32_fu_1086_p2(31 downto 31);
    p_Result_23_fu_1160_p3 <= ret_V_9_fu_1154_p2(32 downto 32);
    p_Result_24_fu_1172_p3 <= ret_V_9_fu_1154_p2(31 downto 31);
    p_Result_25_fu_1240_p3 <= ret_V_10_fu_1234_p2(32 downto 32);
    p_Result_26_fu_1252_p3 <= ret_V_10_fu_1234_p2(31 downto 31);
    p_Result_2_not_i_fu_1278_p2 <= (p_Result_25_fu_1240_p3 xor ap_const_lv1_1);
    p_Result_not_i2_fu_1198_p2 <= (p_Result_23_fu_1160_p3 xor ap_const_lv1_1);
    p_Result_not_i_fu_1028_p2 <= (p_Result_19_fu_989_p3 xor ap_const_lv1_1);
    p_Val2_11_mux_i_fu_875_p3 <= 
        ap_const_lv32_7FFFFFFF when (brmerge5_i_fu_858_p2(0) = '1') else 
        p_Val2_21_reg_1475;
    p_Val2_16_mux_i_fu_954_p3 <= 
        ap_const_lv32_7FFFFFFF when (brmerge8_i_fu_937_p2(0) = '1') else 
        p_Val2_2_reg_1510;
    p_Val2_19_mux_i_fu_1040_p3 <= 
        ap_const_lv32_7FFFFFFF when (brmerge9_i_fu_1022_p2(0) = '1') else 
        p_Val2_28_fu_997_p2;
    p_Val2_1_fu_698_p4 <= ret_V_6_fu_686_p2(43 downto 12);
    p_Val2_1_i_fu_961_p3 <= 
        ap_const_lv32_80000000 when (underflow_6_fu_932_p2(0) = '1') else 
        p_Val2_2_reg_1510;
    p_Val2_20_fu_570_p4 <= ret_V_fu_558_p2(43 downto 12);
    p_Val2_21_fu_600_p2 <= std_logic_vector(unsigned(p_Val2_20_fu_570_p4) + unsigned(tmp_46_i_cast_fu_596_p1));
    p_Val2_23_mux_i_fu_1129_p3 <= 
        ap_const_lv32_7FFFFFFF when (brmerge2_i_fu_1111_p2(0) = '1') else 
        p_Val2_32_fu_1086_p2;
    p_Val2_26_fu_889_p3 <= 
        p_Val2_11_mux_i_fu_875_p3 when (underflow_not_i_fu_869_p2(0) = '1') else 
        p_Val2_i_fu_882_p3;
    p_Val2_28_fu_997_p1 <= reg_273;
    p_Val2_28_fu_997_p2 <= std_logic_vector(signed(p_Val2_26_reg_1539) + signed(p_Val2_28_fu_997_p1));
    p_Val2_2_fu_732_p2 <= std_logic_vector(unsigned(tmp_54_i_cast_fu_728_p1) + unsigned(p_Val2_1_fu_698_p4));
    p_Val2_2_i_fu_1137_p3 <= 
        ap_const_lv32_80000000 when (underflow_8_fu_1105_p2(0) = '1') else 
        p_Val2_32_fu_1086_p2;
    p_Val2_30_fu_968_p3 <= 
        p_Val2_16_mux_i_fu_954_p3 when (underflow_2_not_i_fu_948_p2(0) = '1') else 
        p_Val2_1_i_fu_961_p3;
    p_Val2_32_fu_1086_p1 <= reg_279;
    p_Val2_32_fu_1086_p2 <= std_logic_vector(signed(p_Val2_30_reg_1545) + signed(p_Val2_32_fu_1086_p1));
    p_Val2_34_fu_1168_p1 <= ret_V_9_fu_1154_p2(32 - 1 downto 0);
    p_Val2_36_fu_1248_p1 <= ret_V_10_fu_1234_p2(32 - 1 downto 0);
    p_Val2_3_i_fu_1218_p3 <= 
        ap_const_lv32_80000000 when (underflow_9_fu_1186_p2(0) = '1') else 
        p_Val2_34_fu_1168_p1;
    p_Val2_3_mux_i_fu_1210_p3 <= 
        ap_const_lv32_7FFFFFFF when (brmerge1_i_fu_1192_p2(0) = '1') else 
        p_Val2_34_fu_1168_p1;
    p_Val2_7_i_fu_1298_p3 <= 
        ap_const_lv32_80000000 when (underflow_10_fu_1266_p2(0) = '1') else 
        p_Val2_36_fu_1248_p1;
    p_Val2_7_mux_i_fu_1290_p3 <= 
        ap_const_lv32_7FFFFFFF when (brmerge3_i2_fu_1272_p2(0) = '1') else 
        p_Val2_36_fu_1248_p1;
    p_Val2_i7_fu_1048_p3 <= 
        ap_const_lv32_80000000 when (underflow_7_fu_1016_p2(0) = '1') else 
        p_Val2_28_fu_997_p2;
    p_Val2_i_fu_882_p3 <= 
        ap_const_lv32_80000000 when (underflow_fu_853_p2(0) = '1') else 
        p_Val2_21_reg_1475;
    p_i_fu_668_p2 <= (rev4_fu_650_p2 or not_carry_4_fu_662_p2);
    p_lshr_f_fu_389_p4 <= len_assign_reg_227(31 downto 1);
    p_lshr_fu_369_p4 <= p_neg_fu_363_p2(31 downto 1);
    p_neg_fu_363_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(len_assign_reg_227));
    p_neg_t_fu_383_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_39_fu_379_p1));
    p_not1_i_fu_901_p2 <= (carry_6_reg_1516 xor Range2_all_ones_2_reg_1527);
    p_not2_fu_788_p2 <= (p_Result_17_fu_712_p3 xor ap_const_lv1_1);
    p_not_fu_656_p2 <= (p_Result_14_fu_580_p3 xor ap_const_lv1_1);
    p_not_i_fu_822_p2 <= (carry_4_reg_1481 xor Range2_all_ones_reg_1492);
    phitmp446_demorgan_s_fu_818_p2 <= (carry_4_reg_1481 and Range2_all_ones_reg_1492);
    phitmp_demorgan_i_fu_897_p2 <= (carry_6_reg_1516 and Range2_all_ones_2_reg_1527);
    r_V_2_i_cast_cast_fu_511_p0 <= reg_279;
    r_V_4_fu_540_p0 <= r_V_2_i_cast_cast_fu_511_p0;
    r_V_4_fu_540_p1 <= w_real_V_reg_1428;
    r_V_4_fu_540_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_4_fu_540_p0) * signed(r_V_4_fu_540_p1))), 46));
    r_V_fu_534_p0 <= tmp_42_i_cast_cast_fu_515_p1(13 - 1 downto 0);
    r_V_fu_534_p1 <= r_V_i_cast_cast_fu_501_p1(32 - 1 downto 0);
    r_V_fu_534_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_fu_534_p0) * signed(r_V_fu_534_p1))), 45));
    r_V_i_cast_cast_fu_501_p0 <= reg_273;
        r_V_i_cast_cast_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_i_cast_cast_fu_501_p0),45));

    ret_V_10_fu_1234_p2 <= std_logic_vector(signed(lhs_V_2_fu_1065_p1) - signed(rhs_V_2_fu_1069_p1));
    ret_V_6_fu_686_p2 <= std_logic_vector(unsigned(r_V_reg_1449) + unsigned(tmp_78_reg_1454));
    ret_V_7_fu_983_p2 <= std_logic_vector(signed(lhs_V_fu_976_p1) + signed(rhs_V_fu_980_p1));
    ret_V_8_fu_1072_p2 <= std_logic_vector(signed(lhs_V_2_fu_1065_p1) + signed(rhs_V_2_fu_1069_p1));
    ret_V_9_fu_1154_p2 <= std_logic_vector(signed(lhs_V_fu_976_p1) - signed(rhs_V_fu_980_p1));
    ret_V_fu_558_p2 <= std_logic_vector(unsigned(lhs_V_i_cast_reg_1439) - unsigned(rhs_V_i_cast_reg_1444));
    rev4_fu_650_p2 <= (tmp_77_fu_642_p3 xor ap_const_lv1_1);
    rev5_fu_746_p2 <= (tmp_84_fu_738_p3 xor ap_const_lv1_1);
    rev6_fu_782_p2 <= (tmp_87_fu_774_p3 xor ap_const_lv1_1);
    rev_fu_614_p2 <= (tmp_74_fu_606_p3 xor ap_const_lv1_1);
        rhs_V_2_fu_1069_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_30_reg_1545),33));

        rhs_V_fu_980_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_26_reg_1539),33));

    rhs_V_i_cast_fu_528_p0 <= tmp_24_fu_518_p0;
    rhs_V_i_cast_fu_528_p1 <= tmp_42_i_cast_cast_fu_515_p1(13 - 1 downto 0);
    rhs_V_i_cast_fu_528_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(rhs_V_i_cast_fu_528_p0) * signed(rhs_V_i_cast_fu_528_p1))), 45));
    tmp27_demorgan_fu_842_p2 <= (phitmp446_demorgan_s_fu_818_p2 or brmerge449_demorgan_s_reg_1498);
    tmp27_fu_847_p2 <= (tmp27_demorgan_fu_842_p2 xor ap_const_lv1_1);
    tmp28_fu_864_p2 <= (tmp_50_i_fu_831_p2 or brmerge449_demorgan_s_reg_1498);
    tmp29_demorgan_fu_921_p2 <= (phitmp_demorgan_i_fu_897_p2 or brmerge456_demorgan_s_reg_1533);
    tmp29_fu_926_p2 <= (tmp29_demorgan_fu_921_p2 xor ap_const_lv1_1);
    tmp30_fu_943_p2 <= (tmp_58_i_fu_910_p2 or brmerge456_demorgan_s_reg_1533);
        tmp_19_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_67_fu_312_p4),30));

        tmp_1_i_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_460_p2),64));

    tmp_24_fu_518_p0 <= reg_279;
    tmp_28_fu_306_p2 <= "1" when (tmp_s_fu_300_p2 = ap_const_lv32_0) else "0";
    tmp_29_fu_403_p3 <= 
        p_neg_t_fu_383_p2 when (tmp_66_fu_355_p3(0) = '1') else 
        tmp_40_fu_399_p1;
    tmp_30_fu_326_p2 <= "1" when (signed(i_cast_reg_1314) < signed(grp_fu_262_p2)) else "0";
    tmp_32_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_194),64));
    tmp_33_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_262_p2),64));
    tmp_34_fu_437_p2 <= "1" when (signed(j_assign_cast_fu_433_p1) < signed(tmp_29_reg_1362)) else "0";
    tmp_35_fu_466_p2 <= std_logic_vector(unsigned(i1_reg_239) + unsigned(j_assign_cast_fu_433_p1));
        tmp_36_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_35_fu_466_p2),64));

    tmp_37_fu_478_p2 <= std_logic_vector(unsigned(tmp_29_reg_1362) + unsigned(tmp_35_fu_466_p2));
        tmp_38_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_37_fu_478_p2),64));

    tmp_39_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_fu_369_p4),32));
    tmp_39_i_fu_1180_p2 <= (p_Result_24_fu_1172_p3 xor ap_const_lv1_1);
    tmp_40_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_f_fu_389_p4),32));
    tmp_41_i_fu_1260_p2 <= (p_Result_26_fu_1252_p3 xor ap_const_lv1_1);
        tmp_42_i_cast_cast_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(w_imag_V_reg_1434),45));

    tmp_46_i_cast_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_73_fu_588_p3),32));
    tmp_50_i_fu_831_p2 <= (p_Result_s_reg_1469 xor ap_const_lv1_1);
    tmp_52_i_fu_708_p2 <= std_logic_vector(unsigned(tmp_79_reg_1459) + unsigned(tmp_80_reg_1464));
    tmp_54_i_cast_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_83_fu_720_p3),32));
    tmp_58_i_fu_910_p2 <= (p_Result_16_reg_1504 xor ap_const_lv1_1);
    tmp_59_i_fu_1010_p2 <= (p_Result_20_fu_1002_p3 xor ap_const_lv1_1);
    tmp_61_i_fu_1099_p2 <= (p_Result_22_fu_1091_p3 xor ap_const_lv1_1);
    tmp_66_fu_355_p3 <= len_assign_reg_227(31 downto 31);
    tmp_67_fu_312_p4 <= bit_reg_206(29 downto 1);
    tmp_68_fu_411_p4 <= i1_reg_239(31 downto 6);
    tmp_70_fu_448_p1 <= j_assign_reg_251(26 - 1 downto 0);
    tmp_73_fu_588_p3 <= ret_V_fu_558_p2(11 downto 11);
    tmp_74_fu_606_p3 <= p_Val2_21_fu_600_p2(31 downto 31);
    tmp_77_fu_642_p3 <= ret_V_fu_558_p2(44 downto 44);
    tmp_78_fu_546_p1 <= r_V_4_fu_540_p2(45 - 1 downto 0);
    tmp_79_fu_550_p1 <= r_V_4_fu_540_p2(32 - 1 downto 0);
    tmp_80_fu_554_p1 <= r_V_fu_534_p2(32 - 1 downto 0);
    tmp_83_fu_720_p3 <= tmp_52_i_fu_708_p2(11 downto 11);
    tmp_84_fu_738_p3 <= p_Val2_2_fu_732_p2(31 downto 31);
    tmp_87_fu_774_p3 <= ret_V_6_fu_686_p2(44 downto 44);
    tmp_fu_349_p2 <= "1" when (signed(len_assign_reg_227) > signed(ap_const_lv32_40)) else "0";
    tmp_s_fu_300_p2 <= (j_1_reg_217 and bit_cast_fu_295_p1);
    underflow_10_fu_1266_p2 <= (tmp_41_i_fu_1260_p2 and p_Result_25_fu_1240_p3);
    underflow_2_not_i_fu_948_p2 <= (tmp30_fu_943_p2 or phitmp_demorgan_i_fu_897_p2);
    underflow_6_fu_932_p2 <= (tmp29_fu_926_p2 and p_Result_16_reg_1504);
    underflow_7_fu_1016_p2 <= (tmp_59_i_fu_1010_p2 and p_Result_19_fu_989_p3);
    underflow_8_fu_1105_p2 <= (tmp_61_i_fu_1099_p2 and p_Result_21_fu_1078_p3);
    underflow_9_fu_1186_p2 <= (tmp_39_i_fu_1180_p2 and p_Result_23_fu_1160_p3);
    underflow_fu_853_p2 <= (tmp27_fu_847_p2 and p_Result_s_reg_1469);
    underflow_not_i_fu_869_p2 <= (tmp28_fu_864_p2 or phitmp446_demorgan_s_fu_818_p2);
end behav;
