-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft2d_fixed_top_fft1d_fixed is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_real_ce0 : OUT STD_LOGIC;
    data_real_we0 : OUT STD_LOGIC;
    data_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_real_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_real_ce1 : OUT STD_LOGIC;
    data_real_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_imag_ce0 : OUT STD_LOGIC;
    data_imag_we0 : OUT STD_LOGIC;
    data_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_imag_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_imag_ce1 : OUT STD_LOGIC;
    data_imag_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_199_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_199_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    grp_fu_199_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
    grp_fu_199_p_ce : OUT STD_LOGIC;
    grp_fu_203_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_203_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    grp_fu_203_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
    grp_fu_203_p_ce : OUT STD_LOGIC;
    grp_fu_207_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_207_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    grp_fu_207_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
    grp_fu_207_p_ce : OUT STD_LOGIC;
    grp_fu_211_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_211_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    grp_fu_211_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
    grp_fu_211_p_ce : OUT STD_LOGIC );
end;


architecture behav of fft2d_fixed_top_fft1d_fixed is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv58_1 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln110_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_reg_353 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal data_real_addr_reg_357 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_addr_reg_362 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_real_addr_3_reg_367 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_addr_3_reg_372 : STD_LOGIC_VECTOR (5 downto 0);
    signal len_3_reg_377 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal select_ln119_fu_263_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln119_reg_385 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln118_fu_271_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln118_reg_390 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln118_fu_275_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln118_reg_395 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln118_1_fu_295_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln118_1_reg_403 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln118_fu_299_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln118_reg_408 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_done : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_idle : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_ready : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_j_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_j_4_out_ap_vld : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_idle : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_ready : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce0 : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_we0 : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce1 : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce0 : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_we0 : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce1 : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_din1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_ce : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_din1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_ce : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_din1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_ce : STD_LOGIC;
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_din1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_ce : STD_LOGIC;
    signal i_2_reg_116 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal icmp_ln117_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln100_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal j_4_loc_fu_66 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal data_real_we0_out : STD_LOGIC;
    signal data_imag_we0_out : STD_LOGIC;
    signal zext_ln100_fu_177_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln110_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal i_fu_62 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln100_fu_200_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal len_fu_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal len_4_fu_304_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln118_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_real_ce0_local : STD_LOGIC;
    signal data_real_address0_local : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal data_real_we0_local : STD_LOGIC;
    signal data_imag_ce0_local : STD_LOGIC;
    signal data_imag_address0_local : STD_LOGIC_VECTOR (5 downto 0);
    signal data_imag_we0_local : STD_LOGIC;
    signal zext_ln100_1_fu_182_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln117_fu_217_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_223_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln119_fu_231_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln119_fu_231_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln119_1_fu_237_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal lshr_ln119_2_fu_253_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_223_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln119_1_fu_247_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal lshr_ln119_2_fu_253_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln118_fu_275_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_37_fu_279_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal len_4_fu_304_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_413_ce : STD_LOGIC;
    signal grp_fu_417_ce : STD_LOGIC;
    signal grp_fu_421_ce : STD_LOGIC;
    signal grp_fu_425_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft2d_fixed_top_fft1d_fixed_Pipeline_VITIS_LOOP_103_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        j : IN STD_LOGIC_VECTOR (31 downto 0);
        j_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        j_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component fft2d_fixed_top_fft1d_fixed_Pipeline_VITIS_LOOP_119_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        select_ln119 : IN STD_LOGIC_VECTOR (30 downto 0);
        len : IN STD_LOGIC_VECTOR (31 downto 0);
        empty_43 : IN STD_LOGIC_VECTOR (5 downto 0);
        data_real_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_real_ce0 : OUT STD_LOGIC;
        data_real_we0 : OUT STD_LOGIC;
        data_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_real_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_real_ce1 : OUT STD_LOGIC;
        data_real_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        data_imag_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_imag_ce0 : OUT STD_LOGIC;
        data_imag_we0 : OUT STD_LOGIC;
        data_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_imag_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_imag_ce1 : OUT STD_LOGIC;
        data_imag_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        empty : IN STD_LOGIC_VECTOR (5 downto 0);
        grp_fu_413_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_413_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        grp_fu_413_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
        grp_fu_413_p_ce : OUT STD_LOGIC;
        grp_fu_417_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_din1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        grp_fu_417_p_dout0 : IN STD_LOGIC_VECTOR (44 downto 0);
        grp_fu_417_p_ce : OUT STD_LOGIC;
        grp_fu_421_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_421_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        grp_fu_421_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
        grp_fu_421_p_ce : OUT STD_LOGIC;
        grp_fu_425_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_425_p_din1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        grp_fu_425_p_dout0 : IN STD_LOGIC_VECTOR (43 downto 0);
        grp_fu_425_p_ce : OUT STD_LOGIC );
    end component;


    component fft2d_fixed_top_mul_32s_13s_45_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component fft2d_fixed_top_mul_32s_14s_44_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;



begin
    grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127 : component fft2d_fixed_top_fft1d_fixed_Pipeline_VITIS_LOOP_103_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start,
        ap_done => grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_done,
        ap_idle => grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_idle,
        ap_ready => grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_ready,
        j => j_fu_58,
        j_4_out => grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_j_4_out,
        j_4_out_ap_vld => grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_j_4_out_ap_vld);

    grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133 : component fft2d_fixed_top_fft1d_fixed_Pipeline_VITIS_LOOP_119_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start,
        ap_done => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done,
        ap_idle => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_idle,
        ap_ready => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_ready,
        select_ln119 => select_ln119_reg_385,
        len => len_3_reg_377,
        empty_43 => trunc_ln118_1_reg_403,
        data_real_address0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address0,
        data_real_ce0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce0,
        data_real_we0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_we0,
        data_real_d0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_d0,
        data_real_address1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address1,
        data_real_ce1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce1,
        data_real_q1 => data_real_q1,
        data_imag_address0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address0,
        data_imag_ce0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce0,
        data_imag_we0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_we0,
        data_imag_d0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_d0,
        data_imag_address1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address1,
        data_imag_ce1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce1,
        data_imag_q1 => data_imag_q1,
        empty => trunc_ln118_reg_390,
        grp_fu_413_p_din0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_din0,
        grp_fu_413_p_din1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_din1,
        grp_fu_413_p_dout0 => grp_fu_199_p_dout0,
        grp_fu_413_p_ce => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_ce,
        grp_fu_417_p_din0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_din0,
        grp_fu_417_p_din1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_din1,
        grp_fu_417_p_dout0 => grp_fu_203_p_dout0,
        grp_fu_417_p_ce => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_ce,
        grp_fu_421_p_din0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_din0,
        grp_fu_421_p_din1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_din1,
        grp_fu_421_p_dout0 => grp_fu_207_p_dout0,
        grp_fu_421_p_ce => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_ce,
        grp_fu_425_p_din0 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_din0,
        grp_fu_425_p_din1 => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_din1,
        grp_fu_425_p_dout0 => grp_fu_211_p_dout0,
        grp_fu_425_p_ce => grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln100_fu_162_p2 = ap_const_lv1_0))) then 
                    grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_ready = ap_const_logic_1)) then 
                    grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_ready = ap_const_logic_1)) then 
                    grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_2_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln117_fu_217_p2 = ap_const_lv1_1))) then 
                i_2_reg_116 <= ap_const_lv64_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done = ap_const_logic_1))) then 
                i_2_reg_116 <= add_ln118_reg_408;
            end if; 
        end if;
    end process;

    i_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_62 <= ap_const_lv7_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_fu_62 <= add_ln100_fu_200_p2;
            end if; 
        end if;
    end process;

    j_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                j_fu_58 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_fu_58 <= j_4_loc_fu_66;
            end if; 
        end if;
    end process;

    len_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln100_fu_162_p2 = ap_const_lv1_1))) then 
                len_fu_70 <= ap_const_lv32_2;
            elsif (((icmp_ln118_fu_289_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                len_fu_70 <= len_4_fu_304_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln118_reg_408 <= add_ln118_fu_299_p2;
                trunc_ln118_1_reg_403 <= trunc_ln118_1_fu_295_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                data_imag_addr_3_reg_372 <= zext_ln110_fu_188_p1(6 - 1 downto 0);
                data_imag_addr_reg_362 <= zext_ln100_fu_177_p1(6 - 1 downto 0);
                data_real_addr_3_reg_367 <= zext_ln110_fu_188_p1(6 - 1 downto 0);
                data_real_addr_reg_357 <= zext_ln100_fu_177_p1(6 - 1 downto 0);
                icmp_ln110_reg_353 <= icmp_ln110_fu_194_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_j_4_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                j_4_loc_fu_66 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_j_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                len_3_reg_377 <= len_fu_70;
                select_ln119_reg_385 <= select_ln119_fu_263_p3;
                sext_ln118_reg_395 <= sext_ln118_fu_275_p1;
                trunc_ln118_reg_390 <= trunc_ln118_fu_271_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln110_fu_194_p2, ap_CS_fsm_state4, ap_CS_fsm_state7, ap_CS_fsm_state8, grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_done, grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done, ap_CS_fsm_state10, icmp_ln117_fu_217_p2, ap_CS_fsm_state2, icmp_ln100_fu_162_p2, ap_CS_fsm_state3, icmp_ln118_fu_289_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln100_fu_162_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln110_fu_194_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln117_fu_217_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((icmp_ln118_fu_289_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln100_fu_200_p2 <= std_logic_vector(unsigned(i_fu_62) + unsigned(ap_const_lv7_1));
    add_ln118_fu_299_p2 <= std_logic_vector(signed(sext_ln118_reg_395) + signed(i_2_reg_116));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done)
    begin
        if ((grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_done)
    begin
        if ((grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7, icmp_ln117_fu_217_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln117_fu_217_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, icmp_ln117_fu_217_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln117_fu_217_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    data_imag_address0_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address0, ap_CS_fsm_state10, data_imag_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_imag_address0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address0;
        else 
            data_imag_address0 <= data_imag_address0_local;
        end if; 
    end process;


    data_imag_address0_local_assign_proc : process(ap_CS_fsm_state4, data_imag_addr_reg_362, data_imag_addr_3_reg_372, zext_ln110_fu_188_p1, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            data_imag_address0_local <= data_imag_addr_3_reg_372;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            data_imag_address0_local <= data_imag_addr_reg_362;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_imag_address0_local <= zext_ln110_fu_188_p1(6 - 1 downto 0);
        else 
            data_imag_address0_local <= "XXXXXX";
        end if; 
    end process;

    data_imag_address1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_address1;

    data_imag_ce0_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce0, ap_CS_fsm_state10, data_imag_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_imag_ce0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce0;
        else 
            data_imag_ce0 <= data_imag_ce0_local;
        end if; 
    end process;


    data_imag_ce0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            data_imag_ce0_local <= ap_const_logic_1;
        else 
            data_imag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    data_imag_ce1_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce1, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_imag_ce1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_ce1;
        else 
            data_imag_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    data_imag_d0_assign_proc : process(data_imag_q0, grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_d0, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_imag_d0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_d0;
        else 
            data_imag_d0 <= data_imag_q0;
        end if; 
    end process;


    data_imag_we0_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_we0, ap_CS_fsm_state10, data_imag_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_imag_we0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_imag_we0;
        else 
            data_imag_we0 <= (data_imag_we0_out or ap_const_logic_0);
        end if; 
    end process;


    data_imag_we0_local_assign_proc : process(icmp_ln110_reg_353, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((icmp_ln110_reg_353 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            data_imag_we0_local <= ap_const_logic_1;
        else 
            data_imag_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    data_imag_we0_out <= data_imag_we0_local;

    data_real_address0_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address0, ap_CS_fsm_state10, data_real_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_real_address0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address0;
        else 
            data_real_address0 <= data_real_address0_local;
        end if; 
    end process;


    data_real_address0_local_assign_proc : process(ap_CS_fsm_state4, data_real_addr_reg_357, data_real_addr_3_reg_367, zext_ln110_fu_188_p1, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            data_real_address0_local <= data_real_addr_3_reg_367;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            data_real_address0_local <= data_real_addr_reg_357;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_real_address0_local <= zext_ln110_fu_188_p1(6 - 1 downto 0);
        else 
            data_real_address0_local <= "XXXXXX";
        end if; 
    end process;

    data_real_address1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_address1;

    data_real_ce0_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce0, ap_CS_fsm_state10, data_real_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_real_ce0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce0;
        else 
            data_real_ce0 <= data_real_ce0_local;
        end if; 
    end process;


    data_real_ce0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            data_real_ce0_local <= ap_const_logic_1;
        else 
            data_real_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    data_real_ce1_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce1, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_real_ce1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_ce1;
        else 
            data_real_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    data_real_d0_assign_proc : process(data_real_q0, grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_d0, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_real_d0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_d0;
        else 
            data_real_d0 <= data_real_q0;
        end if; 
    end process;


    data_real_we0_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_we0, ap_CS_fsm_state10, data_real_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            data_real_we0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_data_real_we0;
        else 
            data_real_we0 <= (data_real_we0_out or ap_const_logic_0);
        end if; 
    end process;


    data_real_we0_local_assign_proc : process(icmp_ln110_reg_353, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((icmp_ln110_reg_353 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            data_real_we0_local <= ap_const_logic_1;
        else 
            data_real_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    data_real_we0_out <= data_real_we0_local;
    grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_103_2_fu_127_ap_start_reg;
    grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_ap_start_reg;
    grp_fu_199_p_ce <= grp_fu_413_ce;
    grp_fu_199_p_din0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_din0;
    grp_fu_199_p_din1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_din1;
    grp_fu_203_p_ce <= grp_fu_417_ce;
    grp_fu_203_p_din0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_din0;
    grp_fu_203_p_din1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_din1;
    grp_fu_207_p_ce <= grp_fu_421_ce;
    grp_fu_207_p_din0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_din0;
    grp_fu_207_p_din1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_din1;
    grp_fu_211_p_ce <= grp_fu_425_ce;
    grp_fu_211_p_din0 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_din0;
    grp_fu_211_p_din1 <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_din1;

    grp_fu_413_ce_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_ce, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_413_ce <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_413_p_ce;
        else 
            grp_fu_413_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_417_ce_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_ce, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_417_ce <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_417_p_ce;
        else 
            grp_fu_417_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_421_ce_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_ce, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_421_ce <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_421_p_ce;
        else 
            grp_fu_421_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_425_ce_assign_proc : process(grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_ce, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_425_ce <= grp_fft1d_fixed_Pipeline_VITIS_LOOP_119_5_fu_133_grp_fu_425_p_ce;
        else 
            grp_fu_425_ce <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln100_fu_162_p2 <= "1" when (i_fu_62 = ap_const_lv7_40) else "0";
    icmp_ln110_fu_194_p2 <= "1" when (signed(zext_ln100_1_fu_182_p1) < signed(j_4_loc_fu_66)) else "0";
    icmp_ln117_fu_217_p0 <= len_fu_70;
    icmp_ln117_fu_217_p2 <= "1" when (signed(icmp_ln117_fu_217_p0) < signed(ap_const_lv32_41)) else "0";
    icmp_ln118_fu_289_p2 <= "1" when (signed(tmp_37_fu_279_p4) < signed(ap_const_lv58_1)) else "0";
    len_4_fu_304_p0 <= len_fu_70;
    len_4_fu_304_p2 <= std_logic_vector(shift_left(unsigned(len_4_fu_304_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    lshr_ln119_1_fu_237_p4 <= sub_ln119_fu_231_p2(31 downto 1);
    lshr_ln119_2_fu_253_p1 <= len_fu_70;
    lshr_ln119_2_fu_253_p4 <= lshr_ln119_2_fu_253_p1(31 downto 1);
    select_ln119_fu_263_p3 <= 
        sub_ln119_1_fu_247_p2 when (tmp_fu_223_p3(0) = '1') else 
        lshr_ln119_2_fu_253_p4;
    sext_ln118_fu_275_p0 <= len_fu_70;
        sext_ln118_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln118_fu_275_p0),64));

    sub_ln119_1_fu_247_p2 <= std_logic_vector(unsigned(ap_const_lv31_0) - unsigned(lshr_ln119_1_fu_237_p4));
    sub_ln119_fu_231_p1 <= len_fu_70;
    sub_ln119_fu_231_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(sub_ln119_fu_231_p1));
    tmp_37_fu_279_p4 <= i_2_reg_116(63 downto 6);
    tmp_fu_223_p1 <= len_fu_70;
    tmp_fu_223_p3 <= tmp_fu_223_p1(31 downto 31);
    trunc_ln118_1_fu_295_p1 <= i_2_reg_116(6 - 1 downto 0);
    trunc_ln118_fu_271_p1 <= select_ln119_fu_263_p3(6 - 1 downto 0);
    zext_ln100_1_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_62),32));
    zext_ln100_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_62),64));
    zext_ln110_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_4_loc_fu_66),64));
end behav;
